// Package jobs defines the plugin-side ABI for the background job bus.
//
// The host-side TaskSpec registry + Asynq dispatch lives in
// packages/go/jobs/taskspec and packages/go/jobs/asynq (PRs #355, #362).
// The wazero runtime that loads and runs WebAssembly plugins lives in
// packages/go/plugins/runtime (PR #350). This package is the BRIDGE: it
// describes the well-known function the guest module exports so the
// host can dispatch a queued job invocation into a plugin, and it
// provides the host half that drives that ABI (marshal, allocate, call,
// decode).
//
// # Why a dedicated entry point
//
// A plugin manifest (packages/go/plugins/manifest) lists every job the
// plugin owns in its jobs[] field. At activation time, the lifecycle
// Manager wants to register a TaskSpec for each declared job whose
// Handler proxies through to the plugin. We do NOT want to require the
// guest to export one Go-callable function per job name, because (a)
// that bloats the export table by O(jobs), (b) it forces the toolchain
// to know the manifest at compile time, and (c) it breaks the "register
// at runtime" model that lets a plugin advertise jobs declaratively.
//
// Instead, the plugin exports ONE function — the job handler entry
// point — and the host passes the job name as an argument every time.
// The guest does its own internal demultiplex (typically a switch
// statement generated by the plugin SDK). This is the same pattern used
// by the sibling hook ABI in packages/go/plugins/abi/hooks; the two ABIs
// are intentionally symmetric so plugin SDKs share most of their code.
//
// # The entry point
//
// Every plugin that declares jobs MUST export a function with the
// following signature:
//
//	(func (export "gn_handle_job")
//	      (param $name_ptr i32) (param $name_len i32)
//	      (param $payload_ptr i32) (param $payload_len i32)
//	      (result i64))
//
// Parameters:
//
//   - name_ptr, name_len locate the job name in the guest's exported
//     linear memory (UTF-8, no NUL terminator). The host writes the
//     bytes BEFORE invoking the function and is responsible for
//     allocating space via the guest's gn_alloc export.
//
//   - payload_ptr, payload_len locate the raw payload bytes. The wire
//     format is whatever the producer wrote into the asynq task — by
//     convention JSON, validated against the TaskSpec.PayloadSchema at
//     enqueue time. The bridge does NOT re-encode: payload bytes flow
//     verbatim from the asynq Task to the guest. An empty payload is
//     signalled with payload_len == 0; the guest must accept it.
//
// Return value (packed i64):
//
//   - High 32 bits = result_ptr in guest memory.
//   - Low  32 bits = result_len.
//
// Special values, ordered by precedence (a value matching an earlier
// rule never reaches a later one):
//
//	(ptr=0, len=0)   — success. The job ran to completion.
//	(ptr=0, len=N)   where N is one of the ResultStatus* sentinels —
//	                    the call failed. See ResultStatus for the catalog.
//	otherwise        — success, with an optional result body at
//	                    [ptr, ptr+len) in the guest's exported memory.
//	                    The host reads, copies, and frees the bytes via
//	                    the guest's gn_free export. Result bodies are
//	                    typically empty for jobs — they're fire-and-forget
//	                    by Asynq's contract — but the ABI permits one so
//	                    a future "job that produces an event" pattern can
//	                    be added without an ABI break.
//
// Encoding the result via the return register avoids a second host-bound
// callback (which would complicate the ABI) and keeps the call shape
// callable from any toolchain that can return an i64.
//
// # Allocator exports
//
// Same as the hooks ABI. To pass non-trivial payloads, the host needs
// to write into guest linear memory. wazero exposes the memory directly,
// but the host cannot synthesise an allocation — only the guest knows
// where its free list points. We therefore REQUIRE every plugin to
// export:
//
//	(func (export "gn_alloc") (param i32) (result i32))   ; size -> ptr
//	(func (export "gn_free")  (param i32) (param i32))    ; ptr, size
//
// gn_alloc returns 0 to signal allocation failure (out of memory). The
// host treats a 0 return as ErrOutOfMemory and abandons the call. The
// guest is free to release the bytes immediately (or never); the host
// only calls gn_free for result buffers and only on the successful path.
//
// # Idempotency
//
// Every job invocation carries an idempotency key in its payload
// envelope (see marshal.go). The bridge populates the key from the
// asynq Task ID, which Asynq guarantees is unique per enqueued task —
// even across retries of the same task, the ID is stable. The guest
// can use the key to deduplicate side effects (skip an outbound HTTP
// post the second time, idempotently upsert a row, etc.) without
// having to reach for the platform idempotency store from inside the
// plugin sandbox.
//
// # Errors and traps
//
// Two distinct failure modes — distinguished because the bridge handles
// them differently:
//
//   - "Guest reported an error" — gn_handle_job returned a ResultStatus
//     sentinel. The handler ran to completion but the guest signalled a
//     business-level failure. The bridge returns a JobError wrapping the
//     status; the asynq runner counts it against the task's MaxRetry
//     budget like any other handler error.
//
//   - "Guest trapped" — gn_handle_job never returned (out-of-bounds
//     memory access, divide by zero, gn_panic, OOM during the call,
//     etc.). The runtime catches the trap and the bridge wraps the
//     resulting *TrapError into a JobError tagged ResultStatusTrap.
//     Callers wanting the original trap can errors.As(err, &TrapError).
//     The asynq runner retries trap errors per the spec's policy unless
//     the bridge wraps with asynq.SkipRetry — which it does NOT, because
//     a deterministic trap usually means a real bug and operators want
//     the retry budget to surface it as "this task keeps trapping".
//
// # Versioning
//
// This file is the v1 of the job handler ABI. Any non-additive change
// to the signature (parameter count, return packing, allocator contract)
// will land as a sibling package (abi/jobs/v2, ...) so the v1 surface
// keeps its frozen guarantees.
package jobs

import (
	"errors"
	"fmt"
)

// EntryPoint is the well-known export name every plugin must provide
// for the job handler ABI. The runtime resolves this name via the
// underlying Module's exported-functions table; missing exports surface
// as a runtime.ErrFunctionNotFound when the bridge first tries to call
// it, which the lifecycle Manager turns into a "plugin is incompatible"
// failure at activation.
const EntryPoint = "gn_handle_job"

// AllocExport is the well-known name for the guest's allocator. Returns
// 0 for OOM. The bridge calls it before every job invocation to obtain
// guest memory for the (name, payload) pair. Same export name as the
// hooks ABI — a plugin that owns both hooks and jobs reuses one
// allocator.
const AllocExport = "gn_alloc"

// FreeExport is the well-known name for the guest's deallocator. The
// host calls it on the success path to release the result buffer the
// guest produced (typically empty for jobs).
const FreeExport = "gn_free"

// CapabilityID is the cap a plugin must hold in its manifest to
// register any job. The bridge consults the host-side capability
// Checker at Register time and rejects manifests whose grants do not
// include this cap — better to fail loudly at activation than to wire
// a TaskSpec the worker will refuse to execute.
//
// The cap ID is the same one declared in
// packages/go/plugins/capabilities/registry.go as a built-in cap
// ("jobs.enqueue"). We deliberately gate the BRIDGE (server-side
// registration) on the same cap that gates enqueue: a plugin that
// cannot enqueue should not be allowed to silently receive
// invocations either.
const CapabilityID = "jobs.enqueue"

// MaxJobNameLen caps how many bytes the host will transmit for a job
// name. The manifest schema already constrains job names to a dotted
// lowercase pattern with no single name > 200 chars, but the bridge
// re-validates so a future schema relaxation doesn't blow up the
// allocator. 256 is the runtime-side ceiling, picked to leave one byte
// of slack against the schema cap.
const MaxJobNameLen = 256

// MaxPayloadBytes caps the per-call payload size the host will pass to
// the guest. The asynq layer also enforces an upstream cap (its default
// is a few MiB); 1 MiB is the sensible-job-size ceiling — bigger
// payloads should reach for storage and pass a handle by reference.
//
// A larger payload returns ErrPayloadTooLarge before any guest call.
const MaxPayloadBytes = 1 << 20 // 1 MiB

// MaxResultBytes caps how many bytes the host will read back from the
// guest's returned result pointer. Same sanity-guard rationale as
// MaxPayloadBytes. Set to match: 1 MiB.
const MaxResultBytes = 1 << 20 // 1 MiB

// ResultStatus is the catalog of negative-length sentinels the guest
// can return from gn_handle_job to signal a typed failure. They occupy
// the low 32 bits of the packed return when the high 32 bits (the
// pointer) are zero — picking the (ptr=0, len=sentinel) shape keeps the
// success path's (ptr, len) interpretation untouched.
//
// Sentinels are negative when interpreted as int32 so they can never
// collide with a legitimate length (which is always non-negative). The
// host decodes the low 32 bits as int32 specifically to enable that
// negativity test.
//
// New sentinels MUST be added at the end; existing values are part of
// the frozen ABI and renumbering would break older plugin builds. The
// numbering mirrors the hooks ABI so SDKs that share a status-to-error
// mapping can use one table for both.
type ResultStatus int32

const (
	// ResultStatusOK is the "success, no body" status. It is the normal
	// return for a job handler — asynq's runner cares only that the
	// handler returned without error, so the bridge maps OK to a nil
	// error.
	ResultStatusOK ResultStatus = 0

	// ResultStatusError is the generic guest-reported error. The
	// handler ran but decided the call failed; the bridge surfaces this
	// as a JobError without a more specific cause. The asynq runner
	// counts it against the task's retry budget.
	ResultStatusError ResultStatus = -1

	// ResultStatusOutOfMemory is what the guest returns when its own
	// allocator failed during the handler. The host MAY also synthesise
	// this status when gn_alloc returns 0 for the input buffer, so
	// callers see a single ErrOutOfMemory regardless of which side ran
	// out first.
	ResultStatusOutOfMemory ResultStatus = -2

	// ResultStatusBadPayload indicates the guest could not decode the
	// payload the host sent. This is a contract violation — either the
	// producer enqueued a malformed payload (despite the schema check),
	// or the plugin was built against a different ABI version.
	ResultStatusBadPayload ResultStatus = -3

	// ResultStatusUnknownJob is what the guest returns when its
	// dispatch table has no handler for the requested job name. This
	// shouldn't happen on a correctly-built plugin (the manifest
	// declares which jobs are owned), but a stale plugin binary
	// running against a fresher manifest could produce it.
	ResultStatusUnknownJob ResultStatus = -4

	// ResultStatusTrap is reserved for the host. The guest never
	// returns this; instead the bridge synthesises it when the call
	// trapped (the function never returned at all). It's listed here so
	// the catalog is exhaustive — every JobError carries a status, and
	// trap-derived errors get this one.
	ResultStatusTrap ResultStatus = -5
)

// String returns a short human-readable name for the status. Used in
// error messages and tests; the wire format uses the int32 value.
func (s ResultStatus) String() string {
	switch s {
	case ResultStatusOK:
		return "ok"
	case ResultStatusError:
		return "error"
	case ResultStatusOutOfMemory:
		return "out_of_memory"
	case ResultStatusBadPayload:
		return "bad_payload"
	case ResultStatusUnknownJob:
		return "unknown_job"
	case ResultStatusTrap:
		return "trap"
	default:
		return fmt.Sprintf("status(%d)", int32(s))
	}
}

// IsError reports whether the status indicates a failure. ResultStatusOK
// is the only non-error status; everything else is a failure mode.
func (s ResultStatus) IsError() bool { return s != ResultStatusOK }

// JobError wraps a typed guest-reported (or host-synthesised) failure
// from a job invocation. Status is the categorical reason; Job is the
// job name the bridge was dispatching when the failure occurred; Cause
// is the underlying error (a runtime *TrapError for traps, nil for pure
// status returns).
//
// JobError implements errors.Is against the sentinel package-level
// errors (ErrOutOfMemory, ErrBadPayload, ...) so callers can match
// without type-asserting.
type JobError struct {
	Job    string
	Status ResultStatus
	Cause  error
}

// Error returns a one-line description.
func (e *JobError) Error() string {
	if e.Cause != nil {
		return fmt.Sprintf("abi/jobs: %q: %s: %v", e.Job, e.Status, e.Cause)
	}
	return fmt.Sprintf("abi/jobs: %q: %s", e.Job, e.Status)
}

// Unwrap returns the underlying cause for errors.As traversal — for
// example, errors.As(err, &runtime.TrapError{}) to inspect a trap.
func (e *JobError) Unwrap() error { return e.Cause }

// Is supports errors.Is matching against the sentinel package-level
// errors below. The match is by status, so any JobError with
// ResultStatusOutOfMemory matches ErrOutOfMemory regardless of which
// guest produced it.
func (e *JobError) Is(target error) bool {
	switch target {
	case ErrOutOfMemory:
		return e.Status == ResultStatusOutOfMemory
	case ErrBadPayload:
		return e.Status == ResultStatusBadPayload
	case ErrUnknownJob:
		return e.Status == ResultStatusUnknownJob
	case ErrGuestError:
		return e.Status == ResultStatusError
	case ErrTrapped:
		return e.Status == ResultStatusTrap
	}
	return false
}

// Sentinel errors for matching with errors.Is. Each one corresponds to
// a ResultStatus; the JobError.Is method routes between them.
//
// Callers SHOULD prefer errors.Is over status comparisons so the
// bridge can refactor the underlying status numbering without breaking
// the consumer surface.
var (
	// ErrOutOfMemory is returned (or wrapped) when either the host's
	// allocation into guest memory failed (gn_alloc returned 0) or the
	// guest reported ResultStatusOutOfMemory from inside the handler.
	ErrOutOfMemory = errors.New("abi/jobs: out of memory")

	// ErrBadPayload is returned when the guest reported it could not
	// decode the payload. Indicates an ABI mismatch between host and
	// guest, or a producer-side schema-validation gap.
	ErrBadPayload = errors.New("abi/jobs: bad payload")

	// ErrUnknownJob is returned when the guest reported it has no
	// handler for the requested job name. Typically means the manifest
	// drifted from the binary.
	ErrUnknownJob = errors.New("abi/jobs: unknown job")

	// ErrGuestError is returned when the guest reported a generic
	// failure (ResultStatusError). The catch-all for the plugin
	// signalling "I ran, I failed" without further detail.
	ErrGuestError = errors.New("abi/jobs: guest error")

	// ErrTrapped is returned when the call trapped before the guest
	// could produce a status. The underlying *TrapError is reachable via
	// errors.As on the wrapping JobError.
	ErrTrapped = errors.New("abi/jobs: guest trapped")

	// ErrPayloadTooLarge is returned BEFORE any guest call when the
	// marshalled payload exceeds MaxPayloadBytes. Distinct from
	// ErrOutOfMemory because no allocation was even attempted.
	ErrPayloadTooLarge = errors.New("abi/jobs: payload exceeds host cap")

	// ErrResultTooLarge is returned when the guest's result pointer
	// claims a length greater than MaxResultBytes. The host refuses to
	// read it; the call surfaces as a JobError wrapping this sentinel.
	ErrResultTooLarge = errors.New("abi/jobs: result exceeds host cap")

	// ErrMissingExport is returned when the plugin module does not
	// export one of the required ABI functions (gn_handle_job, gn_alloc,
	// gn_free). It wraps the underlying runtime.ErrFunctionNotFound for
	// callers that want to inspect which export was missing.
	ErrMissingExport = errors.New("abi/jobs: required export missing")

	// ErrMemoryUnavailable is returned when the plugin module does not
	// export linear memory. Without memory the host cannot pass any
	// argument and cannot read any result; the bridge refuses to call.
	ErrMemoryUnavailable = errors.New("abi/jobs: memory unavailable")

	// ErrJobNameTooLong is returned when the job name exceeds
	// MaxJobNameLen bytes. The manifest schema rejects most cases at
	// install time; this is the runtime backstop.
	ErrJobNameTooLong = errors.New("abi/jobs: job name too long")

	// ErrCapabilityDenied is returned by Bridge.Register when the plugin
	// declares jobs in its manifest but does not hold the jobs.enqueue
	// capability. Wraps capabilities.ErrCapabilityDenied so callers can
	// errors.Is either sentinel.
	ErrCapabilityDenied = errors.New("abi/jobs: jobs.enqueue capability denied")
)

// packResult composes the i64 the guest returns from gn_handle_job
// from a (ptr, len) pair. Exported for use by guest SDK helpers and
// tests; host code uses unpackResult on the way back.
//
// Pointer is treated as uint32 (it's a memory offset, always
// non-negative); length is treated as int32 so callers can encode a
// negative ResultStatus by passing (0, int32(status)).
func packResult(ptr uint32, length int32) uint64 {
	return uint64(ptr)<<32 | uint64(uint32(length))
}

// unpackResult is the inverse of packResult. Returns the high-half ptr
// and the low-half length, with length re-interpreted as int32 so a
// negative ResultStatus survives the round trip.
func unpackResult(packed uint64) (ptr uint32, length int32) {
	ptr = uint32(packed >> 32)
	length = int32(packed & 0xFFFFFFFF)
	return ptr, length
}

// jobNameValid is a defense-in-depth check on the name the host is
// about to send to the guest. The manifest schema's regex already gates
// most cases at install time; this catches values that came in from a
// different path (e.g. a test calling InvokeJob directly).
//
// Returns nil for an acceptable name; a wrapped ErrJobNameTooLong or a
// "bad name" error otherwise.
func jobNameValid(name string) error {
	if name == "" {
		return errors.New("abi/jobs: job name is empty")
	}
	if len(name) > MaxJobNameLen {
		return fmt.Errorf("%w: %d > %d", ErrJobNameTooLong, len(name), MaxJobNameLen)
	}
	return nil
}
