/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server identity
         * @description Returns the binary's name, version, and commit. Mounted by cmd/server/main.go.
         */
        get: operations["getRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 unconditionally once the process has started serving. Must
         *     never depend on external state (DB, Redis); a failure here means the
         *     binary itself is unhealthy.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 only when every registered readiness check (DB, Redis)
         *     succeeds. Returns 503 with a per-check breakdown otherwise. Drives
         *     Kubernetes traffic gating.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI 3.1 document
         * @description Returns the embedded OpenAPI 3.1 description as application/json.
         *     Conditional requests are honored via ETag and Last-Modified.
         */
        get: operations["getOpenapiJSON"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI 3.1 document (YAML)
         * @description Same content as /openapi.json, served as YAML. Identical caching
         *     semantics. Convenience surface for tooling that prefers YAML.
         */
        get: operations["getOpenapiYAML"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password + TOTP login
         * @description Exchanges email + password (and optionally TOTP / recovery code) for
         *     a session cookie. The session token is delivered exclusively via the
         *     Set-Cookie header — never echoed in the response body so HttpOnly
         *     keeps its meaning. Returns a 200 with the user id and expiry on
         *     success, or a 200 with an intermediate token when 2FA is required.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the bearer JWT
         * @description Trades a refresh cookie for a short-lived (15m) JWT access token
         *     consumed by the dashboard's API client.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's live sessions */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        /** Revoke every session belonging to the caller */
        delete: operations["revokeAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SessionView.id from listSessions. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a single session */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send an email-verification link
         * @description Generates a fresh verification token, persists its hash in Redis
         *     with a 24h TTL, and queues the verification email. Rate-limited to
         *     one send per minute per user.
         */
        post: operations["sendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consume an email-verification token
         * @description Validates the token from the link the user clicked. Marks the
         *     underlying user row as verified on success. Tokens are single-use.
         */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List personal access tokens */
        get: operations["listTokens"];
        put?: never;
        /**
         * Mint a new personal access token
         * @description Creates a long-lived PAT. The secret is returned ONCE in the response;
         *     subsequent reads only see metadata.
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a personal access token */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List posts */
        get: operations["listPosts"];
        put?: never;
        /** Create a post */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a single post */
        get: operations["getPost"];
        put?: never;
        post?: never;
        /**
         * Trash a post
         * @description Soft-deletes the post (status → trash).
         */
        delete: operations["trashPost"];
        options?: never;
        head?: never;
        /** Update a post */
        patch: operations["updatePost"];
        trace?: never;
    };
    "/api/v1/posts/{id}/autosave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Read the current autosave for a post */
        get: operations["getPostAutosave"];
        put?: never;
        /** Write or replace the autosave for a post */
        post: operations["putPostAutosave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pages */
        get: operations["listPages"];
        put?: never;
        /** Create a page */
        post: operations["createPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a page */
        get: operations["getPage"];
        put?: never;
        post?: never;
        /** Trash a page */
        delete: operations["trashPage"];
        options?: never;
        head?: never;
        /** Update a page */
        patch: operations["updatePage"];
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List comments */
        get: operations["listComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a comment */
        get: operations["getComment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List taxonomy terms */
        get: operations["listTerms"];
        put?: never;
        /** Create a term */
        post: operations["createTerm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a term */
        get: operations["getTerm"];
        put?: never;
        post?: never;
        /** Delete a term */
        delete: operations["deleteTerm"];
        options?: never;
        head?: never;
        /** Update a term */
        patch: operations["updateTerm"];
        trace?: never;
    };
    "/api/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List media library items */
        get: operations["listMedia"];
        put?: never;
        /**
         * Upload a media file
         * @description Accepts a multipart/form-data upload. Persists the binary in the
         *     configured object store, computes derived sizes, and returns the
         *     resulting Media row. This endpoint is in flight — see issue #341.
         */
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a media item */
        get: operations["getMedia"];
        put?: never;
        post?: never;
        /** Delete a media item */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed plugins */
        get: operations["listPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/plugins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a plugin manifest */
        get: operations["getPlugin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/plugins/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a plugin */
        post: operations["activatePlugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/plugins/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a plugin */
        post: operations["deactivatePlugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/plugins/dev/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev-only plugin hot-install
         * @description Hot-installs a plugin from a local manifest. Only mounted when
         *     GONEXT_PLUGINS_DEV_MODE=true. Used by the `gonext plugin dev` CLI's
         *     watch loop. Storage is in-memory: not persisted across restarts.
         */
        post: operations["installPluginDev"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/jobs/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List archived (dead-letter) jobs */
        get: operations["listDeadLetterJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/jobs/dlq/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an archived job */
        get: operations["getDeadLetterJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/jobs/dlq/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-enqueue an archived job */
        post: operations["replayDeadLetterJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/jobs/dlq/{id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently delete an archived job */
        post: operations["discardDeadLetterJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/jobs/dlq/{id}/redact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redact fields in an archived job payload */
        post: operations["redactDeadLetterJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate operational status
         * @description Returns the per-axis health report (DB, Redis, queues, disk, themes,
         *     plugins). Status is always 200; per-source failures are reported in
         *     the body.
         */
        get: operations["getAdminStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rum/percentiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** RUM Web Vitals percentiles */
        get: operations["getRumPercentiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rum/slow-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slowest routes by RUM metric */
        get: operations["getRumSlowRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/rum/beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * RUM beacon endpoint
         * @description Public, unauthenticated beacon used by the theme JS to ship Web
         *     Vitals. Returns 204 on accept. Drops malformed payloads silently.
         */
        post: operations["rumBeacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch site settings */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-resource search */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook subscriptions */
        get: operations["listWebhooks"];
        put?: never;
        /** Create a webhook subscription */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a webhook */
        get: operations["getWebhook"];
        put?: never;
        post?: never;
        /** Delete a webhook */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        /** Update a webhook */
        patch: operations["updateWebhook"];
        trace?: never;
    };
    "/wp-json/wp/v2/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WordPress-compatible posts list */
        get: operations["wpListPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wp-json/wp/v2/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** WordPress-compatible post fetch */
        get: operations["wpGetPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Server identity returned by GET /. Mirrors cmd/server/main.go. */
        Identity: {
            /** @example gonext */
            name: string;
            /**
             * @example v0.1.0
             * @example dev
             */
            version: string;
            /**
             * @example abc1234
             * @example unknown
             */
            commit: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded" | "fail";
            checks?: {
                [key: string]: {
                    status?: string;
                    detail?: string;
                };
            };
        };
        Pagination: {
            next_cursor: string;
            prev_cursor: string;
        };
        /** @description RFC 7807-flavoured error envelope. */
        Error: {
            error: {
                /** Format: uri */
                type?: string;
                title: string;
                status: number;
                code: string;
                detail?: string;
                fields?: {
                    [key: string]: string[];
                };
                trace_id?: string;
            };
        };
        ErrorEnvelope: components["schemas"]["Error"];
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            totp_code?: string;
            recovery_code?: string;
            intermediate_token?: string;
        };
        LoginResponse: {
            user_id: string;
            /** Format: date-time */
            expires_at: string;
        };
        TOTPChallenge: {
            intermediate_token: string;
            requires: ("totp" | "recovery")[];
        };
        AccessToken: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Seconds until expiry. */
            expires_in: number;
        };
        SessionView: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at: string;
            device_label: string;
            ip: string;
            current: boolean;
        };
        SessionList: {
            sessions: components["schemas"]["SessionView"][];
        };
        VerifyResult: {
            verified: boolean;
            user_id: string;
        };
        /** @description Personal access token metadata. The secret is never echoed. */
        Token: {
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            scopes: string[];
        };
        TokenCreate: {
            name: string;
            scopes: string[];
            /** Format: date-time */
            expires_at?: string | null;
        };
        TokenWithSecret: components["schemas"]["Token"] & {
            /**
             * @description The raw token string. Echoed exactly once in the create
             *     response — clients MUST store it now; subsequent reads only
             *     see metadata.
             */
            secret: string;
        };
        /** @description Native REST projection of a row in the posts table. */
        Post: {
            id: string;
            post_type: string;
            parent_id?: string | null;
            author_id: string;
            /** @enum {string} */
            status: "draft" | "publish" | "future" | "pending" | "private" | "trash";
            title: string;
            slug: string;
            excerpt?: string;
            /** @description Canonical block-tree JSON. */
            content_blocks: Record<string, never>;
            /** @enum {string} */
            comment_status: "open" | "closed";
            /** @enum {string} */
            ping_status: "open" | "closed";
            menu_order: number;
            meta: Record<string, never>;
            /** Format: date-time */
            published_at?: string;
            /** Format: date-time */
            scheduled_for?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
            protected: boolean;
        };
        PostCreate: {
            parent_id?: string | null;
            status?: string;
            title?: string;
            slug?: string;
            excerpt?: string;
            content_blocks?: Record<string, never>;
            password?: string;
            comment_status?: string;
            ping_status?: string;
            menu_order?: number;
            meta?: Record<string, never>;
            /** Format: date-time */
            published_at?: string;
            /** Format: date-time */
            scheduled_for?: string;
        };
        PostUpdate: components["schemas"]["PostCreate"];
        PostPage: {
            data: components["schemas"]["Post"][];
            pagination: components["schemas"]["Pagination"];
        };
        Page: components["schemas"]["Post"];
        PageCreate: components["schemas"]["PostCreate"];
        PageUpdate: components["schemas"]["PostCreate"];
        PagePage: {
            data: components["schemas"]["Page"][];
            pagination: components["schemas"]["Pagination"];
        };
        Autosave: {
            post_id: string;
            content_blocks: Record<string, never>;
            title?: string;
            excerpt?: string;
            /** Format: date-time */
            saved_at: string;
        };
        AutosaveInput: {
            content_blocks: Record<string, never>;
            title?: string;
            excerpt?: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            slug?: string;
            /** Format: uri */
            avatar_url?: string;
            roles: string[];
            /** Format: date-time */
            verified_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        UserUpdate: {
            display_name?: string;
            slug?: string;
            /** Format: uri */
            avatar_url?: string;
            roles?: string[];
        };
        UserPage: {
            data: components["schemas"]["User"][];
            pagination: components["schemas"]["Pagination"];
        };
        Comment: {
            id: string;
            post_id: string;
            author_id?: string | null;
            author_name: string;
            /** Format: email */
            author_email?: string;
            /** Format: uri */
            author_url?: string;
            content: string;
            /** @enum {string} */
            status: "approved" | "pending" | "spam" | "trash";
            parent_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CommentPage: {
            data: components["schemas"]["Comment"][];
            pagination: components["schemas"]["Pagination"];
        };
        Term: {
            id: string;
            /** @enum {string} */
            taxonomy: "category" | "post_tag";
            name: string;
            slug: string;
            description?: string;
            parent_id?: string | null;
            count: number;
        };
        TermCreate: {
            /** @enum {string} */
            taxonomy: "category" | "post_tag";
            name: string;
            slug?: string;
            description?: string;
            parent_id?: string | null;
        };
        TermUpdate: {
            name?: string;
            slug?: string;
            description?: string;
            parent_id?: string | null;
        };
        TermPage: {
            data: components["schemas"]["Term"][];
            pagination: components["schemas"]["Pagination"];
        };
        Media: {
            id: string;
            mime: string;
            /** Format: uri */
            url: string;
            byte_size: number;
            width?: number;
            height?: number;
            alt?: string;
            caption?: string;
            sha256?: string;
            uploaded_by?: string;
            /** Format: date-time */
            created_at: string;
        };
        MediaPage: {
            data: components["schemas"]["Media"][];
            pagination: components["schemas"]["Pagination"];
        };
        Plugin: {
            id: string;
            name: string;
            version: string;
            active: boolean;
            author?: string;
            description?: string;
            /** Format: date-time */
            installed_at?: string;
        };
        PluginManifest: {
            id: string;
            version: string;
            entrypoint: string;
            manifest?: Record<string, never>;
        };
        ArchivedTask: {
            id: string;
            queue: string;
            type: string;
            payload_preview: string;
            /**
             * Format: byte
             * @description Present on detail responses; nil on list.
             */
            payload?: string;
            last_error: string;
            /** Format: date-time */
            failed_at?: string;
            retried: number;
            max_retry: number;
            redacted: boolean;
            redacted_fields?: string[];
        };
        RedactRequest: {
            fields: string[];
        };
        /** @description Free-form site options. Keys are stable strings. */
        Settings: {
            [key: string]: unknown;
        };
        SearchResult: {
            /** @enum {string} */
            type: "post" | "page" | "user" | "term" | "media";
            id: string;
            title: string;
            excerpt: string;
            /** Format: uri */
            url?: string;
            score?: number;
        };
        SearchResults: {
            results: components["schemas"]["SearchResult"][];
            total?: number;
        };
        Webhook: {
            id: string;
            /** Format: uri */
            url: string;
            events: string[];
            active: boolean;
            /** @description First 4 chars only. */
            secret_preview?: string;
            /** Format: date-time */
            created_at: string;
        };
        WebhookCreate: {
            /** Format: uri */
            url: string;
            events: string[];
            secret?: string;
            /** @default true */
            active: boolean;
        };
        WebhookUpdate: {
            /** Format: uri */
            url?: string;
            events?: string[];
            active?: boolean;
        };
        RumBeacon: {
            route: string;
            /** @enum {string} */
            metric: "lcp" | "fcp" | "cls" | "inp" | "ttfb";
            value: number;
            device?: string;
            connection?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        RumPercentiles: {
            [key: string]: {
                p50?: number;
                p75?: number;
                p95?: number;
                p99?: number;
                samples?: number;
            };
        };
        RumSlowRoute: {
            route: string;
            value: number;
            samples?: number;
        };
        StatusReport: {
            /** Format: date-time */
            generated_at: string;
            sections: {
                [key: string]: {
                    ok?: boolean;
                    detail?: Record<string, never>;
                    error?: string;
                };
            };
        };
        AuditEvent: {
            id: string;
            event_type: string;
            actor_id: string;
            subject_type?: string;
            subject_id?: string;
            meta?: Record<string, never>;
            /** Format: date-time */
            created_at: string;
        };
        /** @description WordPress-shaped post envelope for /wp-json clients. */
        WPPost: {
            id: number;
            /** Format: date-time */
            date?: string;
            /** Format: date-time */
            date_gmt?: string;
            /** Format: date-time */
            modified?: string;
            /** Format: date-time */
            modified_gmt?: string;
            slug: string;
            status: string;
            type: string;
            /** Format: uri */
            link?: string;
            title: {
                rendered?: string;
            };
            content: {
                rendered?: string;
                protected?: boolean;
            };
            excerpt?: {
                rendered?: string;
            };
            author?: number;
            comment_status?: string;
            ping_status?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required or credentials are invalid. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Caller is authenticated but lacks the capability required. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                "RateLimit-Limit"?: number;
                "RateLimit-Remaining"?: number;
                "RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. Includes a trace_id. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque pagination cursor. */
        Cursor: string;
        /** @description Maximum number of items to return. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description One or more dependencies are unhealthy. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getOpenapiJSON: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document. */
            200: {
                headers: {
                    ETag?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description ETag matched — caller has a fresh copy. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Method not allowed. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOpenapiYAML: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document, YAML serialization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
            /** @description ETag matched. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /**
             * @description Either an authenticated session was established (LoginResponse) or
             *     2FA is required (TOTPChallenge). The client distinguishes by the
             *     shape of the payload.
             */
            200: {
                headers: {
                    /** @description Session cookie on a successful login. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"] | components["schemas"]["TOTPChallenge"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every live session for the authenticated principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked. The caller's session is gone too. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SessionView.id from listSessions. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Send accepted. The email is dispatched asynchronously. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            /** @description Rate limiter unavailable — fail-closed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Token expired or already consumed. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PAT metadata for the authenticated principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tokens: components["schemas"]["Token"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCreate"];
            };
        };
        responses: {
            /** @description Token minted. Secret is in the response body — store it. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenWithSecret"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPosts: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                status?: "draft" | "publish" | "future" | "pending" | "private" | "trash";
                author?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Post created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: {
                /** @description Password for protected posts. See HeaderPostPassword. */
                "X-Post-Password"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested post. */
            200: {
                headers: {
                    ETag?: string;
                    "X-Version"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    trashPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post trashed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optimistic concurrency token (X-Version from last read). */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdate"];
            };
        };
        responses: {
            /** @description Post updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Optimistic concurrency check failed. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPostAutosave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Autosave payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Autosave"];
                };
            };
            /** @description No autosave exists for this post. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putPostAutosave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutosaveInput"];
            };
        };
        responses: {
            /** @description Autosave stored. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listPages: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                status?: "draft" | "publish" | "future" | "pending" | "private" | "trash";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of pages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageCreate"];
            };
        };
        responses: {
            /** @description Page created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    trashPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page trashed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageUpdate"];
            };
        };
        responses: {
            /** @description Page updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted (soft). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description User updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listComments: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by post id. */
                post?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of comments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentPage"];
                };
            };
        };
    };
    getComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested comment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTerms: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                taxonomy?: "category" | "post_tag";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of terms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermPage"];
                };
            };
        };
    };
    createTerm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermCreate"];
            };
        };
        responses: {
            /** @description Term created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTerm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested term. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTerm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Term deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTerm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermUpdate"];
            };
        };
        responses: {
            /** @description Term updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listMedia: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by MIME type (e.g. image/png). */
                mime?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of media items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    alt?: string;
                    caption?: string;
                };
            };
        };
        responses: {
            /** @description Media uploaded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Upload too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested media item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin manifest list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plugins: components["schemas"]["Plugin"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getPlugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin manifest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plugin"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    activatePlugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plugin"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Plugin already active or activation refused. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deactivatePlugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin deactivated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plugin"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    installPluginDev: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PluginManifest"];
            };
        };
        responses: {
            /** @description Plugin installed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plugin"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Endpoint not mounted (dev mode disabled). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDeadLetterJobs: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                queue?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of archived jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tasks: components["schemas"]["ArchivedTask"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getDeadLetterJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived task detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivedTask"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replayDeadLetterJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job re-enqueued. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    discardDeadLetterJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job discarded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    redactDeadLetterJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedactRequest"];
            };
        };
        responses: {
            /** @description Redaction applied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAdminStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational status report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRumPercentiles: {
        parameters: {
            query?: {
                route?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description p50/p75/p95/p99 of LCP, CLS, INP per route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RumPercentiles"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRumSlowRoutes: {
        parameters: {
            query?: {
                metric?: "lcp" | "inp" | "cls" | "fcp" | "ttfb";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Routes ranked by the requested metric. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        routes: components["schemas"]["RumSlowRoute"][];
                    };
                };
            };
        };
    };
    rumBeacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RumBeacon"];
            };
        };
        responses: {
            /** @description Beacon accepted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings map. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Settings updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                type?: ("post" | "page" | "user" | "term" | "media")[];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mixed-type search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook subscriptions for this site. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        webhooks: components["schemas"]["Webhook"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Webhook subscription created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdate"];
            };
        };
        responses: {
            /** @description Webhook updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    wpListPosts: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WordPress-shaped posts collection. */
            200: {
                headers: {
                    "X-WP-Total"?: number;
                    "X-WP-TotalPages"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WPPost"][];
                };
            };
        };
    };
    wpGetPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WordPress-shaped post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WPPost"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
