//! Hook registration and dispatch.
//!
//! [`PluginContext`] is the value plugin authors receive in their
//! `init` function. They call [`PluginContext::register_action`] and
//! [`PluginContext::register_filter`] to advertise the hooks they
//! handle; the dispatcher generated by [`crate::plugin_init!`] turns
//! each invocation from the host into the matching closure call.
//!
//! ## Why a per-instance context rather than a global registry
//!
//! Two reasons:
//!
//!  1. A global table would require a `Mutex` (or `OnceCell`) for the
//!     init path, which complicates `no_std` and forces a runtime
//!     decision about which sync primitive to depend on.
//!
//!  2. The host calls `init` exactly once, single-threaded, before any
//!     hook fires. A per-init scratchpad that we then convert into the
//!     read-only dispatcher is simpler and harder to misuse.
//!
//! See [`crate::plugin_init!`] for how the context gets installed.

use std::boxed::Box;
use std::string::{String, ToString};
use std::vec::Vec;

/// Top-level error type returned by hook handlers. Maps onto the
/// negative-length sentinels the host expects on the failure path.
///
/// Most handlers can simply use `?` against `serde_json::Error` and the
/// `From<serde_json::Error>` impl turns it into the right sentinel
/// ([`SdkError::BadPayload`]).
#[derive(Debug)]
pub enum SdkError {
    /// The handler ran but decided the call failed. Maps onto
    /// [`crate::abi::ResultStatus::Error`].
    Generic(String),
    /// The payload the host sent did not decode as expected. Maps onto
    /// [`crate::abi::ResultStatus::BadPayload`].
    BadPayload(String),
    /// The handler allocated too much. Maps onto
    /// [`crate::abi::ResultStatus::OutOfMemory`].
    OutOfMemory,
}

impl core::fmt::Display for SdkError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            SdkError::Generic(s) => write!(f, "{}", s),
            SdkError::BadPayload(s) => write!(f, "bad payload: {}", s),
            SdkError::OutOfMemory => write!(f, "out of memory"),
        }
    }
}

impl From<serde_json::Error> for SdkError {
    fn from(e: serde_json::Error) -> Self {
        SdkError::BadPayload(e.to_string())
    }
}

impl From<crate::host::HostError> for SdkError {
    fn from(e: crate::host::HostError) -> Self {
        SdkError::Generic(std::format!("host call failed: {}", e))
    }
}

/// Function signature for action handlers. The args slice is the
/// decoded JSON array from the action payload; the handler returns
/// `Ok(())` for success or [`SdkError`] for a typed failure.
pub type ActionHandler = Box<dyn Fn(&[serde_json::Value]) -> Result<(), SdkError>>;

/// Function signature for filter handlers. The value is the
/// transformable value (still in JSON form); the handler returns the
/// transformed value as JSON-encoded bytes, ready for the host to read
/// back.
pub type FilterHandler =
    Box<dyn Fn(&serde_json::Value, &[serde_json::Value]) -> Result<Vec<u8>, SdkError>>;

/// Per-init scratchpad the user populates inside their `init`
/// function. The dispatcher generated by [`crate::plugin_init!`]
/// promotes this into a read-only static after init returns.
pub struct PluginContext {
    actions: Vec<(String, ActionHandler)>,
    filters: Vec<(String, FilterHandler)>,
}

impl PluginContext {
    /// Construct an empty context. The macro-generated `_start`
    /// allocates one of these per-init.
    pub fn new() -> Self {
        Self {
            actions: Vec::new(),
            filters: Vec::new(),
        }
    }

    /// Register an action handler under `name`. The host's hook bus
    /// invokes the closure every time the action fires; the closure
    /// receives the variadic-args slice from the bus.
    ///
    /// Multiple registrations for the same name are last-write-wins —
    /// a plugin should not register the same hook twice, but we don't
    /// trap on it (the manifest validator catches that at install
    /// time).
    pub fn register_action<F>(&mut self, name: impl Into<String>, handler: F)
    where
        F: Fn(&[serde_json::Value]) -> Result<(), SdkError> + 'static,
    {
        self.actions.push((name.into(), Box::new(handler)));
    }

    /// Register a filter handler under `name`. The closure receives
    /// the value being transformed (still as `serde_json::Value` so
    /// the plugin can pick its own typed shape) and the per-call
    /// extras; it returns the JSON-encoded transformed value.
    pub fn register_filter<F>(&mut self, name: impl Into<String>, handler: F)
    where
        F: Fn(&serde_json::Value, &[serde_json::Value]) -> Result<Vec<u8>, SdkError> + 'static,
    {
        self.filters.push((name.into(), Box::new(handler)));
    }

    /// Look up the action handler for `name`. Returns `None` if the
    /// plugin hasn't registered one — the dispatcher maps that onto
    /// [`crate::abi::ResultStatus::UnknownHook`].
    pub fn find_action(&self, name: &str) -> Option<&ActionHandler> {
        self.actions
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, h)| h)
    }

    /// Look up the filter handler for `name`.
    pub fn find_filter(&self, name: &str) -> Option<&FilterHandler> {
        self.filters
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, h)| h)
    }
}

impl Default for PluginContext {
    fn default() -> Self {
        Self::new()
    }
}

/// Allocate `bytes.len()` bytes via the guest's `gn_alloc` export and
/// copy `bytes` into it. Returns the resulting pointer, or 0 if the
/// allocator refused.
///
/// We split this out and gate the `extern "C"` reference on
/// `target_arch = "wasm32"` so the dispatcher itself can be unit-tested
/// on the host architecture. On non-WASM targets the function panics
/// when called from a filter handler — but that path is unreachable in
/// the unit tests we ship (they only exercise UnknownHook / action /
/// BadPayload paths, which never need an allocation).
#[cfg(target_arch = "wasm32")]
fn allocate_result(bytes: &[u8]) -> u32 {
    extern "C" {
        fn gn_alloc(size: u32) -> u32;
    }
    // SAFETY: gn_alloc is generated by plugin_init! and returns a
    // pointer to a buffer of at least `size` bytes (0 means OOM).
    let ptr = unsafe { gn_alloc(bytes.len() as u32) };
    if ptr == 0 {
        return 0;
    }
    // SAFETY: ptr came from our gn_alloc; bytes.len() is the source
    // length we just asked for.
    unsafe {
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr as *mut u8, bytes.len());
    }
    ptr
}

/// Host-architecture fallback. The integration tests cover this:
/// because no filter handler succeeds with a non-empty body in those
/// tests, this function is never actually called. The compile-time
/// symbol exists so the dispatcher is buildable.
#[cfg(not(target_arch = "wasm32"))]
fn allocate_result(_bytes: &[u8]) -> u32 {
    // Returning 0 surfaces as OOM in dispatch — the safest fallback
    // for a host-arch build where the linker has no gn_alloc.
    0
}

/// Dispatch a `gn_handle_hook` call against `ctx` and the host-supplied
/// `(name, payload)`. Returns the packed i64 result the host expects.
///
/// This is the runtime guts of [`crate::plugin_init!`] — the macro
/// generates the `_start`, the allocator exports, and the
/// `gn_handle_hook` extern that funnels into this function.
pub fn dispatch(ctx: &PluginContext, name: &str, payload: &[u8]) -> u64 {
    use crate::abi::{pack_ok, pack_result, pack_status, ResultStatus};
    use crate::codec::{decode_action_payload, decode_filter_payload, PayloadKind};

    // Peek at the envelope's "kind" field without decoding the full
    // shape — we need to dispatch action vs filter and we don't yet
    // know which.
    //
    // serde_json::from_slice is cheap; the kind discriminator is the
    // first field, so the parser bails out after a few hundred bytes
    // in the typical case. Two decodes is fine here.
    #[derive(serde::Deserialize)]
    struct Kind {
        kind: PayloadKind,
    }
    let kind = match serde_json::from_slice::<Kind>(payload) {
        Ok(k) => k.kind,
        Err(_) => return pack_status(ResultStatus::BadPayload),
    };

    match kind {
        PayloadKind::Action => {
            let handler = match ctx.find_action(name) {
                Some(h) => h,
                None => return pack_status(ResultStatus::UnknownHook),
            };
            let ap = match decode_action_payload(payload) {
                Ok(p) => p,
                Err(_) => return pack_status(ResultStatus::BadPayload),
            };
            match handler(&ap.args) {
                Ok(()) => pack_ok(),
                Err(SdkError::BadPayload(_)) => pack_status(ResultStatus::BadPayload),
                Err(SdkError::OutOfMemory) => pack_status(ResultStatus::OutOfMemory),
                Err(SdkError::Generic(_)) => pack_status(ResultStatus::Error),
            }
        }
        PayloadKind::Filter => {
            let handler = match ctx.find_filter(name) {
                Some(h) => h,
                None => return pack_status(ResultStatus::UnknownHook),
            };
            let fp = match decode_filter_payload(payload) {
                Ok(p) => p,
                Err(_) => return pack_status(ResultStatus::BadPayload),
            };
            match handler(&fp.value, &fp.args) {
                Ok(bytes) => {
                    // Allocate guest memory for the result so the host
                    // can read it after we return. The allocator
                    // generated by plugin_init! owns the bytes — we
                    // don't free here; the host calls gn_free on the
                    // success path.
                    let len = bytes.len();
                    if len == 0 {
                        return pack_ok();
                    }
                    let ptr = allocate_result(&bytes);
                    if ptr == 0 {
                        return pack_status(ResultStatus::OutOfMemory);
                    }
                    pack_result(ptr, len as i32)
                }
                Err(SdkError::BadPayload(_)) => pack_status(ResultStatus::BadPayload),
                Err(SdkError::OutOfMemory) => pack_status(ResultStatus::OutOfMemory),
                Err(SdkError::Generic(_)) => pack_status(ResultStatus::Error),
            }
        }
    }
}
