package redirects

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Allowed HTTP redirect status codes. We pin this set (rather than
// "any 3xx") because the table's CHECK constraint pins it too — the
// store rejects unknown codes at the API surface so the failure is
// "your input was wrong" instead of "your database write failed".
var allowedStatuses = map[int]struct{}{
	301: {},
	302: {},
	307: {},
	308: {},
}

// Errors returned by Store implementations. Callers errors.Is against
// these sentinels rather than string-match the wrapped error text.
var (
	// ErrInvalidRule is returned by Create/Update when a rule's fields
	// fail validation (empty source/destination, unknown status,
	// uncompilable regex). The store does not persist invalid rules.
	ErrInvalidRule = errors.New("redirects: invalid rule")

	// ErrDuplicate is returned by Create when a rule with the same
	// (source_path, is_regex) already exists. Translates to HTTP 409
	// at the admin handler.
	ErrDuplicate = errors.New("redirects: duplicate rule")

	// ErrNotFound is returned by Get/Update/Delete when no rule
	// matches the given ID. Translates to HTTP 404.
	ErrNotFound = errors.New("redirects: rule not found")
)

// Rule is the canonical representation of a redirect rule, matching
// the redirects table 1:1.
type Rule struct {
	ID              uuid.UUID
	SourcePath      string
	DestinationPath string

	// Status is one of 301/302/307/308. Zero = invalid.
	Status int

	// IsRegex toggles between literal lookup and regex iteration. A
	// rule is one or the other for its entire lifetime — flipping is
	// an Update.
	IsRegex bool

	HitCount  int64
	LastHitAt time.Time
	CreatedAt time.Time
	CreatedBy uuid.NullUUID
}

// HitDelta carries a buffered "hits since last flush" counter for one
// rule. The engine accumulates these in-memory and hands them to the
// Store via BulkIncrementHits in a single transaction every 30s.
type HitDelta struct {
	RuleID    uuid.UUID
	Count     int64
	LastHitAt time.Time
}

// validateForCreate runs the structural checks the store applies before
// persisting a rule. Centralized so both Postgres and InMemory enforce
// the exact same contract — there is no "well, the in-memory store is
// lenient" trap waiting in tests.
func validateForCreate(r Rule) error {
	if len(r.SourcePath) == 0 {
		return fmt.Errorf("%w: source_path empty", ErrInvalidRule)
	}
	if len(r.DestinationPath) == 0 {
		return fmt.Errorf("%w: destination_path empty", ErrInvalidRule)
	}
	if _, ok := allowedStatuses[r.Status]; !ok {
		return fmt.Errorf("%w: status %d not in {301,302,307,308}", ErrInvalidRule, r.Status)
	}
	return nil
}

// Store is the persistence contract for redirect rules. Implementations
// MUST be safe for concurrent use from many goroutines: the engine
// holds a single Store reference and may interleave Snapshot reads
// (called once at boot, but also when the operator clicks "reload")
// with BulkIncrementHits writes (called every 30s by the engine's
// flusher).
type Store interface {
	// Create persists rule. The Rule.ID is generated by the store and
	// returned in the response — callers passing in a zero ID is the
	// expected path. Returns ErrInvalidRule on structural failure or
	// ErrDuplicate on uniqueness violation.
	Create(ctx context.Context, rule Rule) (Rule, error)

	// Get fetches a single rule by ID. Returns ErrNotFound if absent.
	Get(ctx context.Context, id uuid.UUID) (Rule, error)

	// Update replaces the editable fields (source/destination/status/
	// is_regex) for the rule with the given ID. Hit counters are NOT
	// touched — they are append-only counters maintained by
	// BulkIncrementHits. Returns ErrNotFound if no rule matches.
	Update(ctx context.Context, rule Rule) (Rule, error)

	// Delete removes the rule with the given ID. Returns nil even
	// when no rule matches: the operator pressing Delete twice is not
	// an error from the operator's point of view (the rule is
	// definitely gone after either call).
	Delete(ctx context.Context, id uuid.UUID) error

	// List returns rules in created_at DESC order. Pagination is
	// cursor-based on created_at; callers pass the lower bound from
	// the previous page's last row. limit caps the result; zero
	// requests the store default (50).
	List(ctx context.Context, before time.Time, limit int) ([]Rule, error)

	// Snapshot returns every rule in the table. Called by the engine
	// at boot and on operator-triggered reload. Order is stable on
	// created_at ASC so regex rules iterate in creation order.
	Snapshot(ctx context.Context) ([]Rule, error)

	// BulkIncrementHits applies the given deltas in a single atomic
	// operation. Implementations MUST clamp negative deltas to zero
	// (the engine never decrements, but defense in depth) and update
	// last_hit_at to the maximum of the existing value and the
	// supplied LastHitAt. Empty input is a no-op.
	BulkIncrementHits(ctx context.Context, deltas []HitDelta) error
}

// pgxQuerier is the subset of *pgxpool.Pool the PgxStore uses. Exposed
// so tests can fake the pool surface and so callers can hand in a
// pgx.Tx when they want to write rules inside a larger transaction.
type pgxQuerier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	Exec(ctx context.Context, sql string, args ...any) (cmdTag, error)
}

// cmdTag is the tiny shim that hides pgconn.CommandTag from the
// querier interface — see packages/go/settings/postgres.go for the
// same pattern. We only need RowsAffected().
type cmdTag interface {
	RowsAffected() int64
}

// poolAdapter wraps *pgxpool.Pool to satisfy pgxQuerier.
type poolAdapter struct{ pool *pgxpool.Pool }

func (a poolAdapter) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	return a.pool.QueryRow(ctx, sql, args...)
}

func (a poolAdapter) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	return a.pool.Query(ctx, sql, args...)
}

func (a poolAdapter) Exec(ctx context.Context, sql string, args ...any) (cmdTag, error) {
	tag, err := a.pool.Exec(ctx, sql, args...)
	if err != nil {
		return nil, err
	}
	return tagWrapper{tag.RowsAffected()}, nil
}

type tagWrapper struct{ rows int64 }

func (t tagWrapper) RowsAffected() int64 { return t.rows }

// PgxStore is the production Store backed by Postgres via pgx.
type PgxStore struct {
	db pgxQuerier
}

// NewPgxStore wraps a *pgxpool.Pool in the production Store. The pool
// is borrowed (not owned); the caller is responsible for closing it
// at shutdown.
func NewPgxStore(pool *pgxpool.Pool) *PgxStore {
	return &PgxStore{db: poolAdapter{pool: pool}}
}

// newPgxStoreFromQuerier is the test-side constructor. Not exported.
func newPgxStoreFromQuerier(q pgxQuerier) *PgxStore {
	return &PgxStore{db: q}
}

const insertSQL = `
INSERT INTO redirects (source_path, destination_path, status, is_regex, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, hit_count, last_hit_at, created_at
`

// Create inserts a new rule. The id/hit_count/created_at fields are
// populated from the RETURNING clause.
func (s *PgxStore) Create(ctx context.Context, rule Rule) (Rule, error) {
	if err := validateForCreate(rule); err != nil {
		return Rule{}, err
	}
	var (
		id        uuid.UUID
		hitCount  int64
		lastHit   *time.Time
		createdAt time.Time
	)
	row := s.db.QueryRow(ctx, insertSQL,
		rule.SourcePath, rule.DestinationPath, rule.Status, rule.IsRegex, rule.CreatedBy,
	)
	if err := row.Scan(&id, &hitCount, &lastHit, &createdAt); err != nil {
		// Postgres surfaces UNIQUE violations as a pgconn error with
		// SQLState 23505. We sniff the string here rather than import
		// pgconn just for one code, since callers only care about the
		// sentinel.
		if isUniqueViolation(err) {
			return Rule{}, fmt.Errorf("%w: source=%q is_regex=%t", ErrDuplicate, rule.SourcePath, rule.IsRegex)
		}
		return Rule{}, fmt.Errorf("redirects: insert: %w", err)
	}
	out := rule
	out.ID = id
	out.HitCount = hitCount
	if lastHit != nil {
		out.LastHitAt = *lastHit
	}
	out.CreatedAt = createdAt
	return out, nil
}

const selectByIDSQL = `
SELECT id, source_path, destination_path, status, is_regex,
       hit_count, last_hit_at, created_at, created_by
FROM redirects
WHERE id = $1
`

// Get fetches one rule by ID.
func (s *PgxStore) Get(ctx context.Context, id uuid.UUID) (Rule, error) {
	row := s.db.QueryRow(ctx, selectByIDSQL, id)
	out, err := scanRule(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Rule{}, fmt.Errorf("%w: id=%s", ErrNotFound, id)
		}
		return Rule{}, fmt.Errorf("redirects: get: %w", err)
	}
	return out, nil
}

const updateSQL = `
UPDATE redirects
SET source_path = $2, destination_path = $3, status = $4, is_regex = $5
WHERE id = $1
RETURNING hit_count, last_hit_at, created_at, created_by
`

// Update mutates the editable fields of an existing rule.
func (s *PgxStore) Update(ctx context.Context, rule Rule) (Rule, error) {
	if err := validateForCreate(rule); err != nil {
		return Rule{}, err
	}
	if rule.ID == uuid.Nil {
		return Rule{}, fmt.Errorf("%w: zero ID", ErrInvalidRule)
	}
	var (
		hitCount  int64
		lastHit   *time.Time
		createdAt time.Time
		createdBy uuid.NullUUID
	)
	row := s.db.QueryRow(ctx, updateSQL,
		rule.ID, rule.SourcePath, rule.DestinationPath, rule.Status, rule.IsRegex,
	)
	if err := row.Scan(&hitCount, &lastHit, &createdAt, &createdBy); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Rule{}, fmt.Errorf("%w: id=%s", ErrNotFound, rule.ID)
		}
		if isUniqueViolation(err) {
			return Rule{}, fmt.Errorf("%w: source=%q is_regex=%t", ErrDuplicate, rule.SourcePath, rule.IsRegex)
		}
		return Rule{}, fmt.Errorf("redirects: update: %w", err)
	}
	out := rule
	out.HitCount = hitCount
	if lastHit != nil {
		out.LastHitAt = *lastHit
	}
	out.CreatedAt = createdAt
	out.CreatedBy = createdBy
	return out, nil
}

const deleteSQL = `DELETE FROM redirects WHERE id = $1`

// Delete removes a rule. Idempotent.
func (s *PgxStore) Delete(ctx context.Context, id uuid.UUID) error {
	if _, err := s.db.Exec(ctx, deleteSQL, id); err != nil {
		return fmt.Errorf("redirects: delete: %w", err)
	}
	return nil
}

const listSQL = `
SELECT id, source_path, destination_path, status, is_regex,
       hit_count, last_hit_at, created_at, created_by
FROM redirects
WHERE ($1::TIMESTAMPTZ IS NULL OR created_at < $1)
ORDER BY created_at DESC
LIMIT $2
`

// List returns a page of rules. before may be the zero time.
func (s *PgxStore) List(ctx context.Context, before time.Time, limit int) ([]Rule, error) {
	if limit <= 0 || limit > 500 {
		limit = 50
	}
	var beforeArg any
	if !before.IsZero() {
		beforeArg = before
	}
	rows, err := s.db.Query(ctx, listSQL, beforeArg, limit)
	if err != nil {
		return nil, fmt.Errorf("redirects: list: %w", err)
	}
	defer rows.Close()
	out := make([]Rule, 0, limit)
	for rows.Next() {
		r, err := scanRule(rows)
		if err != nil {
			return nil, fmt.Errorf("redirects: list scan: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

const snapshotSQL = `
SELECT id, source_path, destination_path, status, is_regex,
       hit_count, last_hit_at, created_at, created_by
FROM redirects
ORDER BY created_at ASC
`

// Snapshot returns every rule. The engine calls this at boot and on
// operator-triggered reload.
func (s *PgxStore) Snapshot(ctx context.Context) ([]Rule, error) {
	rows, err := s.db.Query(ctx, snapshotSQL)
	if err != nil {
		return nil, fmt.Errorf("redirects: snapshot: %w", err)
	}
	defer rows.Close()
	out := make([]Rule, 0, 64)
	for rows.Next() {
		r, err := scanRule(rows)
		if err != nil {
			return nil, fmt.Errorf("redirects: snapshot scan: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// BulkIncrementHits applies deltas in a single UPDATE statement using
// VALUES + JOIN. The implementation collapses repeated rule IDs into
// one row before sending so we don't pay for redundant lock contention
// on hot rules. Empty input is a no-op.
func (s *PgxStore) BulkIncrementHits(ctx context.Context, deltas []HitDelta) error {
	if len(deltas) == 0 {
		return nil
	}
	// Collapse duplicates first — an engine flush usually has one
	// HitDelta per rule, but defensive coalescing means a buggy caller
	// can't blow up the SQL.
	type acc struct {
		count int64
		last  time.Time
	}
	merged := make(map[uuid.UUID]acc, len(deltas))
	for _, d := range deltas {
		if d.Count <= 0 {
			continue
		}
		a := merged[d.RuleID]
		a.count += d.Count
		if d.LastHitAt.After(a.last) {
			a.last = d.LastHitAt
		}
		merged[d.RuleID] = a
	}
	if len(merged) == 0 {
		return nil
	}
	ids := make([]uuid.UUID, 0, len(merged))
	counts := make([]int64, 0, len(merged))
	lasts := make([]time.Time, 0, len(merged))
	for id, a := range merged {
		ids = append(ids, id)
		counts = append(counts, a.count)
		lasts = append(lasts, a.last)
	}
	const sql = `
UPDATE redirects AS r
SET hit_count   = r.hit_count + d.cnt,
    last_hit_at = GREATEST(r.last_hit_at, d.lst)
FROM unnest($1::uuid[], $2::bigint[], $3::timestamptz[]) AS d(id, cnt, lst)
WHERE r.id = d.id
`
	if _, err := s.db.Exec(ctx, sql, ids, counts, lasts); err != nil {
		return fmt.Errorf("redirects: bulk-increment: %w", err)
	}
	return nil
}

// scanRule reads one redirects row from a pgx.Row OR a pgx.Rows. Both
// expose Scan with the same shape, so a tiny interface lets us share.
func scanRule(s interface {
	Scan(dest ...any) error
}) (Rule, error) {
	var (
		out       Rule
		lastHit   *time.Time
		createdBy uuid.NullUUID
	)
	if err := s.Scan(
		&out.ID, &out.SourcePath, &out.DestinationPath, &out.Status, &out.IsRegex,
		&out.HitCount, &lastHit, &out.CreatedAt, &createdBy,
	); err != nil {
		return Rule{}, err
	}
	if lastHit != nil {
		out.LastHitAt = *lastHit
	}
	out.CreatedBy = createdBy
	return out, nil
}

// isUniqueViolation returns true when err looks like Postgres
// SQLState 23505. We keep this string-based to avoid dragging pgconn
// into the package surface; a brittle string check is fine for one
// well-known error code.
func isUniqueViolation(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	// pgconn embeds "(SQLSTATE 23505)" in the wrapped error string.
	return contains(msg, "23505") || contains(msg, "duplicate key")
}

func contains(s, sub string) bool {
	return len(sub) > 0 && len(s) >= len(sub) && indexOf(s, sub) >= 0
}

func indexOf(s, sub string) int {
	// Tiny inline search — we don't want to import strings just for
	// the unique-violation sniff. The needle is short (5 chars) and
	// the haystack is a pgx error string, so this is fine.
	n := len(sub)
	for i := 0; i+n <= len(s); i++ {
		if s[i:i+n] == sub {
			return i
		}
	}
	return -1
}

// =============================================================================
// InMemoryStore
// =============================================================================

// InMemoryStore is a Store backed by a sync.RWMutex-guarded map. It's
// intended for tests and short-lived development environments — there
// is no persistence and no eviction.
type InMemoryStore struct {
	mu    sync.RWMutex
	rules map[uuid.UUID]Rule

	// nowFunc replaces time.Now for tests that want deterministic
	// CreatedAt values.
	nowFunc func() time.Time
}

// NewInMemoryStore returns an empty store ready for use.
func NewInMemoryStore() *InMemoryStore {
	return &InMemoryStore{rules: make(map[uuid.UUID]Rule)}
}

// SetNowFunc overrides time.Now. For tests only.
func (s *InMemoryStore) SetNowFunc(fn func() time.Time) {
	s.mu.Lock()
	s.nowFunc = fn
	s.mu.Unlock()
}

func (s *InMemoryStore) now() time.Time {
	if s.nowFunc != nil {
		return s.nowFunc()
	}
	return time.Now()
}

// Create persists a rule. Generates a new UUID v7-ish (uuid.New) ID
// regardless of any value the caller supplied — the store, not the
// caller, owns IDs.
func (s *InMemoryStore) Create(_ context.Context, rule Rule) (Rule, error) {
	if err := validateForCreate(rule); err != nil {
		return Rule{}, err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	// Uniqueness on (source, is_regex).
	for _, r := range s.rules {
		if r.SourcePath == rule.SourcePath && r.IsRegex == rule.IsRegex {
			return Rule{}, fmt.Errorf("%w: source=%q is_regex=%t", ErrDuplicate, rule.SourcePath, rule.IsRegex)
		}
	}
	rule.ID = uuid.New()
	rule.CreatedAt = s.now()
	rule.HitCount = 0
	rule.LastHitAt = time.Time{}
	s.rules[rule.ID] = rule
	return rule, nil
}

func (s *InMemoryStore) Get(_ context.Context, id uuid.UUID) (Rule, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	r, ok := s.rules[id]
	if !ok {
		return Rule{}, fmt.Errorf("%w: id=%s", ErrNotFound, id)
	}
	return r, nil
}

func (s *InMemoryStore) Update(_ context.Context, rule Rule) (Rule, error) {
	if err := validateForCreate(rule); err != nil {
		return Rule{}, err
	}
	if rule.ID == uuid.Nil {
		return Rule{}, fmt.Errorf("%w: zero ID", ErrInvalidRule)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	existing, ok := s.rules[rule.ID]
	if !ok {
		return Rule{}, fmt.Errorf("%w: id=%s", ErrNotFound, rule.ID)
	}
	// Enforce uniqueness on (source, is_regex) — but the rule's own
	// row is allowed to keep the same value.
	for id, r := range s.rules {
		if id == rule.ID {
			continue
		}
		if r.SourcePath == rule.SourcePath && r.IsRegex == rule.IsRegex {
			return Rule{}, fmt.Errorf("%w: source=%q is_regex=%t", ErrDuplicate, rule.SourcePath, rule.IsRegex)
		}
	}
	// Preserve hit counters + provenance; only editable fields move.
	existing.SourcePath = rule.SourcePath
	existing.DestinationPath = rule.DestinationPath
	existing.Status = rule.Status
	existing.IsRegex = rule.IsRegex
	s.rules[rule.ID] = existing
	return existing, nil
}

func (s *InMemoryStore) Delete(_ context.Context, id uuid.UUID) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.rules, id)
	return nil
}

func (s *InMemoryStore) List(_ context.Context, before time.Time, limit int) ([]Rule, error) {
	if limit <= 0 || limit > 500 {
		limit = 50
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	all := make([]Rule, 0, len(s.rules))
	for _, r := range s.rules {
		if !before.IsZero() && !r.CreatedAt.Before(before) {
			continue
		}
		all = append(all, r)
	}
	sort.Slice(all, func(i, j int) bool {
		return all[i].CreatedAt.After(all[j].CreatedAt)
	})
	if len(all) > limit {
		all = all[:limit]
	}
	return all, nil
}

func (s *InMemoryStore) Snapshot(_ context.Context) ([]Rule, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]Rule, 0, len(s.rules))
	for _, r := range s.rules {
		out = append(out, r)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].CreatedAt.Before(out[j].CreatedAt)
	})
	return out, nil
}

func (s *InMemoryStore) BulkIncrementHits(_ context.Context, deltas []HitDelta) error {
	if len(deltas) == 0 {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, d := range deltas {
		if d.Count <= 0 {
			continue
		}
		r, ok := s.rules[d.RuleID]
		if !ok {
			// Rule was deleted between match-time and flush-time. Not
			// fatal — the delta is dropped on the floor, which is the
			// honest answer ("we can't credit hits to a row that no
			// longer exists").
			continue
		}
		r.HitCount += d.Count
		if d.LastHitAt.After(r.LastHitAt) {
			r.LastHitAt = d.LastHitAt
		}
		s.rules[d.RuleID] = r
	}
	return nil
}
