package migrate

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// replacementsUsage is the help text for `gonext migrate replacements`.
const replacementsUsage = `gonext migrate replacements — emit a Markdown
report of GoNext equivalents for WordPress plugins.

Usage:
  gonext migrate replacements --plugins=<slug>[,<slug>...] [--out=PATH]
  gonext migrate replacements --scan=<wp-content/plugins> [--out=PATH]

Flags:
  --plugins string  Comma-separated list of WP plugin slugs.
  --scan    string  Directory to scan for plugin subdirectories. Each
                    direct child is treated as a slug.
  --out     string  Output file. Default: replacement-report.md in CWD.

Exit codes:
  0   report generated
  1   IO error
  2   usage error

The 'covered' status reflects today's roadmap; see the published
plugin equivalents page in the docs for the live version.`

// runReplacements is the entry point for `gonext migrate replacements`.
func runReplacements(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("migrate replacements", flag.ContinueOnError)
	fs.SetOutput(stderr)
	var (
		pluginsFlag string
		scanFlag    string
		outFlag     string
	)
	fs.StringVar(&pluginsFlag, "plugins", "", "Comma-separated WP plugin slugs")
	fs.StringVar(&scanFlag, "scan", "", "Directory containing WP plugin subdirectories")
	fs.StringVar(&outFlag, "out", "replacement-report.md", "Output file path")
	fs.Usage = func() { fmt.Fprintln(stderr, replacementsUsage) }
	if err := fs.Parse(args); err != nil {
		return ExitUsage
	}
	if pluginsFlag == "" && scanFlag == "" {
		fmt.Fprintln(stderr, replacementsUsage)
		fmt.Fprintln(stderr, "")
		fmt.Fprintln(stderr, "gonext migrate replacements: provide --plugins or --scan")
		return ExitUsage
	}

	var slugs []string
	if pluginsFlag != "" {
		slugs = parsePluginsList(pluginsFlag)
	}
	if scanFlag != "" {
		scanned, err := scanPluginsDir(scanFlag)
		if err != nil {
			fmt.Fprintf(stderr, "gonext migrate replacements: scan %q: %v\n", scanFlag, err)
			return ExitFail
		}
		slugs = mergeSlugs(slugs, scanned)
	}
	if len(slugs) == 0 {
		fmt.Fprintln(stderr, "gonext migrate replacements: no plugins to report on")
		return ExitUsage
	}

	report := buildReport(slugs)
	if err := os.WriteFile(outFlag, []byte(report), 0o644); err != nil {
		fmt.Fprintf(stderr, "gonext migrate replacements: write %q: %v\n", outFlag, err)
		return ExitFail
	}
	fmt.Fprintf(stdout, "wrote %s (%d plugins)\n", outFlag, len(slugs))
	return ExitOK
}

// parsePluginsList splits a comma-separated slug list, trims
// whitespace, and drops empty entries.
func parsePluginsList(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return dedupe(out)
}

// scanPluginsDir lists the immediate subdirectories of dir. Each
// subdir name is taken as a plugin slug — the standard layout for
// wp-content/plugins/.
func scanPluginsDir(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, ".") {
			continue // skip dotted (e.g. .DS_Store, .git)
		}
		out = append(out, name)
	}
	return dedupe(out), nil
}

// mergeSlugs appends b to a, deduping. Order from a is preserved;
// new slugs from b are appended in the order they appear.
func mergeSlugs(a, b []string) []string {
	seen := make(map[string]struct{}, len(a))
	out := make([]string, 0, len(a)+len(b))
	for _, s := range a {
		if _, ok := seen[s]; !ok {
			seen[s] = struct{}{}
			out = append(out, s)
		}
	}
	for _, s := range b {
		if _, ok := seen[s]; !ok {
			seen[s] = struct{}{}
			out = append(out, s)
		}
	}
	return out
}

// dedupe removes duplicates while preserving first-seen order.
func dedupe(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if _, ok := seen[s]; !ok {
			seen[s] = struct{}{}
			out = append(out, s)
		}
	}
	return out
}

// buildReport assembles the Markdown report for slugs in their input
// order. Each plugin slot becomes a "## <Title>" section.
func buildReport(slugs []string) string {
	var b strings.Builder
	b.WriteString("# WordPress plugin replacement guide\n\n")
	b.WriteString("Generated by `gonext migrate replacements`. ")
	b.WriteString("Each plugin below maps to a GoNext equivalent ")
	b.WriteString("with notes on coverage and migration steps.\n\n")
	b.WriteString("Status legend:\n\n")
	b.WriteString("- **Built-in** — covered by GoNext core today.\n")
	b.WriteString("- **Plugin** — covered by an official GoNext plugin.\n")
	b.WriteString("- **Planned** — on the roadmap; track the linked issue.\n")
	b.WriteString("- **No equivalent yet** — no GoNext story; consider keeping the WP install around for this surface.\n\n")
	b.WriteString("## Summary\n\n")
	b.WriteString("| Slug | Replacement | Status |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, slug := range slugs {
		e := LookupReplacement(slug)
		b.WriteString("| `")
		b.WriteString(slug)
		b.WriteString("` | ")
		b.WriteString(e.Replacement)
		b.WriteString(" | ")
		b.WriteString(string(e.Status))
		b.WriteString(" |\n")
	}
	b.WriteString("\n## Details\n\n")
	for _, slug := range slugs {
		e := LookupReplacement(slug)
		b.WriteString("### ")
		b.WriteString(e.Title)
		b.WriteString(" (`")
		b.WriteString(slug)
		b.WriteString("`)\n\n")
		b.WriteString("**Status:** ")
		b.WriteString(string(e.Status))
		b.WriteString("\n\n")
		b.WriteString("**Replacement:** ")
		b.WriteString(e.Replacement)
		b.WriteString("\n\n")
		if e.Notes != "" {
			b.WriteString(e.Notes)
			b.WriteString("\n\n")
		}
		if e.Link != "" {
			b.WriteString("Reference: ")
			b.WriteString(e.Link)
			b.WriteString("\n\n")
		}
	}
	return b.String()
}

// ReplacementStatus is the coverage tier for a WP plugin in GoNext.
type ReplacementStatus string

const (
	// StatusBuiltIn means GoNext core ships the feature.
	StatusBuiltIn ReplacementStatus = "Built-in"

	// StatusPlugin means an official GoNext plugin covers it.
	StatusPlugin ReplacementStatus = "Plugin"

	// StatusPlanned means it's on the roadmap.
	StatusPlanned ReplacementStatus = "Planned"

	// StatusNone means there is no GoNext equivalent.
	StatusNone ReplacementStatus = "No equivalent yet"

	// StatusUnknown is the default for slugs not in the registry.
	StatusUnknown ReplacementStatus = "Unknown plugin"
)

// ReplacementEntry is one row of the curated registry.
type ReplacementEntry struct {
	Title       string
	Replacement string
	Status      ReplacementStatus
	Notes       string
	Link        string
}

// registry is the curated WP-plugin → GoNext equivalent map. The
// list is kept small and opinionated: ~30 of the most-installed
// plugins on wordpress.org plus a few niche ones the team has
// migration plans for.
//
// Order: slugs are looked up case-insensitively; the canonical form
// stored here is the WP slug.
var registry = map[string]ReplacementEntry{
	// Custom fields
	"advanced-custom-fields": {
		Title:       "Advanced Custom Fields",
		Replacement: "GoNext core fields (`packages/go/migrate/acf`)",
		Status:      StatusBuiltIn,
		Notes:       "ACF JSON exports are mapped to GoNext field-group schemas by the migrator. Common field types (text, image, repeater, post_object, user, true_false) survive the round trip; presentational ACF widgets (tab, accordion, message) are dropped with a warning.",
		Link:        "https://github.com/Singleton-Solution/GoNext/issues/207",
	},
	"acf": {
		Title:       "Advanced Custom Fields (alt slug)",
		Replacement: "GoNext core fields (`packages/go/migrate/acf`)",
		Status:      StatusBuiltIn,
		Notes:       "Same coverage as `advanced-custom-fields`.",
		Link:        "https://github.com/Singleton-Solution/GoNext/issues/207",
	},
	// Forms
	"wpforms-lite": {
		Title:       "WPForms",
		Replacement: "GoNext core forms (planned)",
		Status:      StatusPlanned,
		Notes:       "GoNext's forms surface is on the roadmap. Until it lands, retain WPForms by running the WP install in proxy mode for form submissions only.",
		Link:        "https://github.com/Singleton-Solution/GoNext/issues/240",
	},
	"contact-form-7": {
		Title:       "Contact Form 7",
		Replacement: "GoNext core forms (planned)",
		Status:      StatusPlanned,
		Notes:       "Same disposition as WPForms — the forms surface is shared.",
		Link:        "https://github.com/Singleton-Solution/GoNext/issues/240",
	},
	"gravityforms": {
		Title:       "Gravity Forms",
		Replacement: "GoNext core forms (planned)",
		Status:      StatusPlanned,
		Notes:       "Premium form builder; the GoNext core forms scope is form-builder shaped, but advanced Gravity entries (conditional logic on per-field-rule, payments integration) are out of scope for v1.",
		Link:        "https://github.com/Singleton-Solution/GoNext/issues/240",
	},
	// SEO
	"wordpress-seo": {
		Title:       "Yoast SEO",
		Replacement: "GoNext SEO plugin (`examples/plugins/seo`)",
		Status:      StatusPlugin,
		Notes:       "The bundled SEO plugin covers title / description / OG tags and sitemap generation. Yoast's premium features (redirect manager, focus-keyword analysis) are out of scope; the redirect manager has its own GoNext surface (`/redirects` in admin).",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/examples/plugins/seo",
	},
	"seo-by-rank-math": {
		Title:       "Rank Math SEO",
		Replacement: "GoNext SEO plugin (`examples/plugins/seo`)",
		Status:      StatusPlugin,
		Notes:       "Same coverage as Yoast; Rank Math's schema markup overlaps with the SEO plugin's JSON-LD output.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/examples/plugins/seo",
	},
	"all-in-one-seo-pack": {
		Title:       "All in One SEO",
		Replacement: "GoNext SEO plugin (`examples/plugins/seo`)",
		Status:      StatusPlugin,
		Notes:       "Same coverage as Yoast / Rank Math.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/examples/plugins/seo",
	},
	// E-commerce
	"woocommerce": {
		Title:       "WooCommerce",
		Replacement: "No equivalent yet",
		Status:      StatusNone,
		Notes:       "GoNext has no e-commerce surface today. The recommended migration path is to keep WooCommerce on a /shop subdomain backed by the existing WP install and run GoNext for content / marketing pages only. The roadmap tracks a long-horizon e-commerce surface.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/ROADMAP.md#e-commerce",
	},
	"easy-digital-downloads": {
		Title:       "Easy Digital Downloads",
		Replacement: "No equivalent yet",
		Status:      StatusNone,
		Notes:       "Same disposition as WooCommerce — see roadmap.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/ROADMAP.md#e-commerce",
	},
	// Page builders
	"elementor": {
		Title:       "Elementor",
		Replacement: "GoNext block editor (core)",
		Status:      StatusBuiltIn,
		Notes:       "Elementor content is HTML; the importer's `html2blocks` pass converts it to GoNext blocks. Custom widget output that depends on the Elementor renderer at request time will fall back to raw HTML in a `core/html` block — visual parity is best-effort.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/migrate/html2blocks",
	},
	"beaver-builder-lite-version": {
		Title:       "Beaver Builder",
		Replacement: "GoNext block editor (core)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as Elementor — `html2blocks` handles the export.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/migrate/html2blocks",
	},
	"siteorigin-panels": {
		Title:       "Page Builder by SiteOrigin",
		Replacement: "GoNext block editor (core)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as Elementor.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/migrate/html2blocks",
	},
	"divi-builder": {
		Title:       "Divi Builder",
		Replacement: "GoNext block editor (core)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as Elementor. Divi's shortcode-style markup is unwound by `html2blocks`.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/migrate/html2blocks",
	},
	// Caching / perf
	"wp-super-cache": {
		Title:       "WP Super Cache",
		Replacement: "GoNext core (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "GoNext serves content from the renderer with HTTP caching headers; no separate page-cache plugin is needed. CDN integration is configured per-deployment.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/docs/01-architecture-overview.md",
	},
	"w3-total-cache": {
		Title:       "W3 Total Cache",
		Replacement: "GoNext core (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as WP Super Cache.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/docs/01-architecture-overview.md",
	},
	"wp-rocket": {
		Title:       "WP Rocket",
		Replacement: "GoNext core (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as WP Super Cache. Image optimisation is handled by the bundled libvips path.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/docs/01-architecture-overview.md",
	},
	"litespeed-cache": {
		Title:       "LiteSpeed Cache",
		Replacement: "GoNext core (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/docs/01-architecture-overview.md",
	},
	// Security
	"wordfence": {
		Title:       "Wordfence Security",
		Replacement: "GoNext core auth + WAF (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "GoNext's auth path (argon2id passwords, OAuth, TOTP, PAT scopes) and edge WAF cover the firewall + brute-force protection bases. Wordfence's malware scanner has no GoNext equivalent — GoNext runs no PHP, so the scan surface doesn't apply.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/auth",
	},
	"sucuri-scanner": {
		Title:       "Sucuri Security",
		Replacement: "GoNext core (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as Wordfence.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/auth",
	},
	"limit-login-attempts-reloaded": {
		Title:       "Limit Login Attempts Reloaded",
		Replacement: "GoNext core (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "Brute-force lockout is built into the auth path; configurable per-deployment.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/auth",
	},
	// Backups
	"updraftplus": {
		Title:       "UpdraftPlus",
		Replacement: "Operator tooling (`gonext backup`)",
		Status:      StatusBuiltIn,
		Notes:       "Use `gonext backup` (or your platform's snapshot tooling) for database + media backups. Cross-site sync targets (S3, Dropbox, Google Drive) are the operator's responsibility — there's no per-installation plugin.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/docs/12-operations.md",
	},
	// Media / images
	"smush": {
		Title:       "Smush Image Compression",
		Replacement: "GoNext core media pipeline (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "The media path runs libvips with WebP/AVIF transcoding by default. The `/img/{id}/{spec}` route handles on-the-fly transforms (resize, crop, format).",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/media",
	},
	"ewww-image-optimizer": {
		Title:       "EWWW Image Optimizer",
		Replacement: "GoNext core media pipeline (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as Smush.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/media",
	},
	"imagify": {
		Title:       "Imagify",
		Replacement: "GoNext core media pipeline (built-in)",
		Status:      StatusBuiltIn,
		Notes:       "Same disposition as Smush.",
		Link:        "https://github.com/Singleton-Solution/GoNext/tree/main/packages/go/media",
	},
	// Redirects
	"redirection": {
		Title:       "Redirection",
		Replacement: "GoNext core redirects (`/redirects` admin)",
		Status:      StatusBuiltIn,
		Notes:       "Literal and regex redirects (301/302/307/308) are managed in the admin. The migrator imports an existing Redirection plugin's rule set when the WP export includes it.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/migrations/000027_redirects.up.sql",
	},
	// Analytics
	"google-analytics-for-wordpress": {
		Title:       "MonsterInsights",
		Replacement: "GoNext analytics (RUM + Performance)",
		Status:      StatusBuiltIn,
		Notes:       "Built-in RUM tracking ships Core Web Vitals to the Performance admin surface. For full Google Analytics, embed gtag via the SEO plugin's `<head>` injector.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/apps/admin/src/app/(authenticated)/performance",
	},
	// Misc
	"jetpack": {
		Title:       "Jetpack",
		Replacement: "Mixed",
		Status:      StatusBuiltIn,
		Notes:       "Jetpack bundles many features; most have GoNext equivalents (CDN, related posts, contact form, stats). Some (VaultPress backup, Akismet) require external services. See the bundle-by-feature breakdown linked below.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/docs/08-migration-compat.md",
	},
	"akismet": {
		Title:       "Akismet Anti-Spam",
		Replacement: "GoNext comments + 3rd-party Akismet API",
		Status:      StatusPlanned,
		Notes:       "GoNext's comment surface has spam-flagging hooks; an Akismet plugin is on the roadmap. Until it lands, manual moderation is the recommended path.",
		Link:        "https://github.com/Singleton-Solution/GoNext/issues/241",
	},
	"polylang": {
		Title:       "Polylang (multilingual)",
		Replacement: "No equivalent yet",
		Status:      StatusNone,
		Notes:       "Multilingual content is on the long-horizon roadmap. Retain Polylang on the WP install for translated pages until then.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/ROADMAP.md",
	},
	"wpml": {
		Title:       "WPML (multilingual)",
		Replacement: "No equivalent yet",
		Status:      StatusNone,
		Notes:       "Same disposition as Polylang.",
		Link:        "https://github.com/Singleton-Solution/GoNext/blob/main/ROADMAP.md",
	},
}

// LookupReplacement returns the registry entry for a plugin slug,
// case-insensitively. Slugs not in the registry get a "best effort"
// fallback entry with status StatusUnknown.
func LookupReplacement(slug string) ReplacementEntry {
	if e, ok := registry[strings.ToLower(slug)]; ok {
		return e
	}
	return ReplacementEntry{
		Title:       titleizeSlug(slug),
		Replacement: "Not in registry — check the published plugin equivalents page.",
		Status:      StatusUnknown,
		Notes:       "This plugin slug isn't yet on the curated list. File an issue or check the docs for migration guidance.",
		Link:        "https://github.com/Singleton-Solution/GoNext/issues/new",
	}
}

// titleizeSlug turns "advanced-custom-fields" into
// "Advanced Custom Fields" for the fallback report title.
func titleizeSlug(s string) string {
	if s == "" {
		return "(unnamed)"
	}
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, " ")
}

// RegistrySlugs returns the curated slug list in lexicographic order
// for tests and for the `--list-known` future flag.
func RegistrySlugs() []string {
	out := make([]string, 0, len(registry))
	for s := range registry {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

// resolvedOutPath cleans the output path so an absent directory
// component yields a sensible diagnostic instead of a panic. Exposed
// for tests; production callers route through runReplacements.
func resolvedOutPath(p string) string {
	if p == "" {
		return "replacement-report.md"
	}
	return filepath.Clean(p)
}
