package importer

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/Singleton-Solution/GoNext/packages/go/migrate/wxr"
)

// upsertUser writes a wxr.Author into users + user_passwords. The
// natural key is the email; we fall back to the handle when the
// WXR row has no email (rare but observed in fixtures). The
// migrated user carries meta.must_reset_password=true so the
// login flow can force a reset before any session is issued.
//
// Returns nil on success (under any ConflictPolicy that allows a
// row to be considered "imported"), ErrAborted on
// ConflictPolicy=Fail conflicts, and a wrapped error on SQL
// failures.
func (imp *Importer) upsertUser(
	ctx context.Context,
	tx pgx.Tx,
	opts Options,
	state *runState,
	a *wxr.Author,
) error {
	email, handle := normaliseIdentity(a)
	if email == "" && handle == "" {
		return errors.New("author has no email or login")
	}

	// Build the meta JSON. We carry the wp_author_id for any
	// downstream tooling that needs to round-trip back to the
	// original WP export.
	metaMap := map[string]any{
		"must_reset_password": true,
		"wp_author_id":        a.ID,
		"wp_author_login":     a.Login,
	}
	if a.FirstName != "" {
		metaMap["first_name"] = a.FirstName
	}
	if a.LastName != "" {
		metaMap["last_name"] = a.LastName
	}
	metaJSON, err := json.Marshal(metaMap)
	if err != nil {
		return fmt.Errorf("marshal user meta: %w", err)
	}

	display := a.DisplayName
	if display == "" {
		display = handle
	}

	// Existence check via the natural key. We can't use a single
	// ON CONFLICT statement because the user_passwords companion
	// row needs the same id, and pgx doesn't surface "did the
	// upsert insert or update?" cleanly across drivers. A two-
	// step probe is simpler and still cheap for an import where
	// each user appears once.
	var existingID uuid.UUID
	err = tx.QueryRow(ctx, `
		SELECT id FROM users
		 WHERE ($1::citext <> '' AND email = $1::citext)
		    OR ($2::citext <> '' AND handle = $2::citext)
		 LIMIT 1
	`, email, handle).Scan(&existingID)
	switch {
	case err == nil:
		// Row exists — apply conflict policy.
		state.recordAuthor(a, existingID)
		switch opts.OnConflict {
		case ConflictSkip:
			return nil
		case ConflictUpdate:
			if _, uErr := tx.Exec(ctx, `
				UPDATE users
				   SET display_name = $1,
				       meta = meta || $2::jsonb
				 WHERE id = $3
			`, display, string(metaJSON), existingID); uErr != nil {
				return fmt.Errorf("update user: %w", uErr)
			}
			return nil
		case ConflictFail:
			return fmt.Errorf("user already exists: email=%q handle=%q: %w",
				email, handle, ErrAborted)
		}
	case errors.Is(err, pgx.ErrNoRows):
		// Fall through to insert.
	default:
		return fmt.Errorf("probe user: %w", err)
	}

	// Insert. The id is generated by gen_uuid_v7(); we read it
	// back via RETURNING so the runState map gets the canonical
	// value and not a parallel guess.
	var newID uuid.UUID
	insertEmail := email
	if insertEmail == "" {
		// users.email is NOT NULL. Synthesize a deterministic
		// placeholder so the row survives the import; the operator
		// can fix it from the admin afterwards. The placeholder
		// uses the .invalid TLD (RFC 2606) so it never collides
		// with a real address.
		insertEmail = handle + "@migrated.invalid"
	}
	insertHandle := handle
	if insertHandle == "" {
		insertHandle = strings.Split(email, "@")[0]
	}
	if err := tx.QueryRow(ctx, `
		INSERT INTO users (email, handle, display_name, meta)
		VALUES ($1::citext, $2::citext, $3, $4::jsonb)
		RETURNING id
	`, insertEmail, insertHandle, display, string(metaJSON)).Scan(&newID); err != nil {
		// Unique violation race: another writer beat us. Re-probe
		// and treat as "exists" per the chosen policy.
		var pgErr interface{ SQLState() string }
		if errors.As(err, &pgErr) && pgErr.SQLState() == "23505" {
			if rErr := tx.QueryRow(ctx, `
				SELECT id FROM users
				 WHERE email = $1::citext OR handle = $2::citext
				 LIMIT 1
			`, insertEmail, insertHandle).Scan(&existingID); rErr == nil {
				state.recordAuthor(a, existingID)
				return nil
			}
		}
		return fmt.Errorf("insert user: %w", err)
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO user_passwords (user_id, password_hash)
		VALUES ($1, $2)
		ON CONFLICT (user_id) DO NOTHING
	`, newID, opts.PlaceholderPasswordHash); err != nil {
		return fmt.Errorf("insert user_passwords: %w", err)
	}

	state.recordAuthor(a, newID)
	return nil
}

// normaliseIdentity trims whitespace off email and login and
// returns canonical (email, handle) values for the upsert. The
// import has no other lever to normalise WP data (we deliberately
// don't lowercase here — citext does it in the DB), so this
// stays small.
func normaliseIdentity(a *wxr.Author) (email, handle string) {
	return strings.TrimSpace(a.Email), strings.TrimSpace(a.Login)
}

// findOrCreateMigratedUser looks up the synthetic "migrated"
// author or creates it on demand. Used as a fallback when a Post
// references a creator login the WXR preamble never declared
// (rare, but legal — admin tools sometimes strip authors).
func (imp *Importer) findOrCreateMigratedUser(
	ctx context.Context,
	tx pgx.Tx,
	opts Options,
	state *runState,
) (uuid.UUID, error) {
	const fallbackLogin = "migrated"
	if id, ok := state.lookupAuthorByLogin(fallbackLogin); ok {
		return id, nil
	}
	stub := &wxr.Author{
		ID:          "0",
		Login:       fallbackLogin,
		Email:       "migrated@migrated.invalid",
		DisplayName: "Migrated User",
	}
	if err := imp.upsertUser(ctx, tx, opts, state, stub); err != nil {
		return uuid.UUID{}, err
	}
	id, _ := state.lookupAuthorByLogin(fallbackLogin)
	return id, nil
}
