package password

import (
	"errors"
	"strings"
	"testing"
)

// phpassFixtures are password / encoded-hash pairs produced by the
// phpass algorithm exactly as implemented in
// wp-includes/class-phpass.php. They are deliberately generated by
// this package's own algorithm (the algorithm is a faithful line-by-
// line port of the WordPress source — see phpass.go for the citation)
// because we want round-trip determinism without depending on a PHP
// runtime in CI.
//
// Each fixture exercises a different character class so the encoder's
// edge cases (empty input, multi-byte UTF-8, whitespace) are covered.
var phpassFixtures = []struct {
	password string
	encoded  string
}{
	{password: "hello-world", encoded: "$P$BabcdefghfXGCmqWPePm9zxMQTxmWf0"},
	{password: "correct horse battery staple", encoded: "$P$B12345678uMkEEiNXlW9rq2Nl1y1cs."},
	{password: "password", encoded: "$P$BsaltsaltnH1n4.V11.zjFlE3mwm.O1"},
	{password: "", encoded: "$P$BemptypwdjZkYScCXHF6/6t3Oq69s31"},
	{password: "unicode-密码-🔑", encoded: "$P$BuniSALT8TAd8n/Of4GGNPxckeuNtI/"},
}

func TestVerifyPhpass_Roundtrip(t *testing.T) {
	t.Parallel()
	for _, c := range phpassFixtures {
		t.Run(c.password, func(t *testing.T) {
			ok, err := VerifyPhpass(c.password, c.encoded)
			if err != nil {
				t.Fatalf("verify: %v", err)
			}
			if !ok {
				t.Fatalf("verify returned ok=false for matching password %q", c.password)
			}
		})
	}
}

func TestVerifyPhpass_WrongPassword(t *testing.T) {
	t.Parallel()
	enc := "$P$BabcdefghfXGCmqWPePm9zxMQTxmWf0" // for "hello-world"
	wrong := []string{
		"hello-world ", // trailing space
		"Hello-World",  // case
		"helloworld",   // missing dash
		"",             // empty
	}
	for _, w := range wrong {
		t.Run(w, func(t *testing.T) {
			ok, err := VerifyPhpass(w, enc)
			if err != nil {
				t.Fatalf("verify: %v", err)
			}
			if ok {
				t.Fatalf("verify returned ok=true for wrong password %q", w)
			}
		})
	}
}

func TestIsPhpass(t *testing.T) {
	t.Parallel()
	cases := []struct {
		in   string
		want bool
	}{
		{"$P$BabcdefghfXGCmqWPePm9zxMQTxmWf0", true},
		{"$H$BabcdefghfXGCmqWPePm9zxMQTxmWf0", true}, // Drupal fork prefix
		{"", false},
		{"$argon2id$v=19$m=65536,t=3,p=2$AAAAAAAAAAAAAAAAAAAAAA$BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA", false},
		{"$2a$10$...", false}, // bcrypt
		{"plaintext", false},
		{"$P$", false}, // prefix only, too short
	}
	for _, c := range cases {
		if got := IsPhpass(c.in); got != c.want {
			t.Errorf("IsPhpass(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestVerifyPhpass_NotPhpass(t *testing.T) {
	t.Parallel()
	ok, err := VerifyPhpass("password", "$argon2id$v=19$m=65536,t=3,p=2$AAAA$BBBB")
	if ok {
		t.Errorf("ok must be false")
	}
	if !errors.Is(err, ErrNotPhpass) {
		t.Errorf("err: got %v want ErrNotPhpass", err)
	}
}

func TestVerifyPhpass_Malformed(t *testing.T) {
	t.Parallel()
	cases := []string{
		"$P$Babcd",                                  // too short overall
		"$P$" + strings.Repeat("x", 100),            // too long
		"$P$#abcdefgh" + strings.Repeat("a", 22),    // cost char not in alphabet (# index = -1, rejected)
		"$P$/abcdefgh" + strings.Repeat("a", 22),    // cost char index 0, below floor 7
	}
	for i, c := range cases {
		ok, err := VerifyPhpass("password", c)
		if ok {
			t.Errorf("[%d] ok must be false for malformed %q", i, c)
		}
		if err == nil {
			t.Errorf("[%d] want error for malformed %q", i, c)
		}
		if !errors.Is(err, ErrPhpassMalformed) && !errors.Is(err, ErrNotPhpass) {
			// "$P$Babcd" matches the prefix but is too short; expect
			// ErrPhpassMalformed. Other shapes may report ErrNotPhpass
			// when they fail the prefix check; both are acceptable.
			t.Errorf("[%d] err type: %v", i, err)
		}
	}
}

// TestVerifyPhpass_PasswordNotEchoed ensures the password never leaks
// into error messages. This is a defence-in-depth check the package
// already guarantees by construction, but we pin it explicitly so a
// future maintainer can't accidentally regress.
func TestVerifyPhpass_PasswordNotEchoed(t *testing.T) {
	t.Parallel()
	pw := "super-secret-must-not-appear"
	_, err := VerifyPhpass(pw, "$P$Babcd") // malformed -> error
	if err == nil {
		t.Fatal("want error")
	}
	if strings.Contains(err.Error(), pw) {
		t.Fatalf("password leaked into error: %v", err)
	}
}

func TestPhpassEncode64_Length(t *testing.T) {
	t.Parallel()
	// 16-byte input must always produce 22-char output.
	in := make([]byte, 16)
	for i := range in {
		in[i] = byte(i)
	}
	out := phpassEncode64(in, 16)
	if got, want := len(out), 22; got != want {
		t.Errorf("encode64 length: got %d want %d", got, want)
	}
}
