// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Input for the createPost mutation.
type CreatePostInput struct {
	Title   string      `json:"title"`
	Slug    string      `json:"slug"`
	Excerpt *string     `json:"excerpt,omitempty"`
	Status  *PostStatus `json:"status,omitempty"`
}

// Top-level mutations. Phase 1 covers post creation only.
type Mutation struct {
}

// Standard Relay PageInfo. `endCursor` is empty when there is no next page.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor,omitempty"`
	EndCursor       *Cursor `json:"endCursor,omitempty"`
}

// A piece of content. The Post type here is the union of fields shared
// by all content types; the full content surface (pages, terms, media)
// extends Node / Content interfaces — those land in a follow-up issue.
type Post struct {
	ID       string     `json:"id"`
	Title    string     `json:"title"`
	Slug     string     `json:"slug"`
	Status   PostStatus `json:"status"`
	Excerpt  *string    `json:"excerpt,omitempty"`
	AuthorID string     `json:"authorID"`
	// Author of the post. Batched via dataloader to avoid N+1 lookups.
	Author      *User     `json:"author"`
	CreatedAt   DateTime  `json:"createdAt"`
	UpdatedAt   DateTime  `json:"updatedAt"`
	PublishedAt *DateTime `json:"publishedAt,omitempty"`
}

// Cursor-paginated Post list. Standard Relay shape.
type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
	// Total count of items matching the filter. May be expensive — clients should only request when they intend to render a count.
	TotalCount int `json:"totalCount"`
}

type PostEdge struct {
	Cursor Cursor `json:"cursor"`
	Node   *Post  `json:"node"`
}

// Filter parameters for `posts`. All fields are AND-combined.
type PostFilter struct {
	// Filter by status. Omitted = published only (the public default).
	Status *PostStatus `json:"status,omitempty"`
	// Filter by author ID.
	AuthorID *string `json:"authorID,omitempty"`
	// Free-text title prefix match.
	TitlePrefix *string `json:"titlePrefix,omitempty"`
}

// The currently authenticated user, plus content lookups. Every field
// is capability-gated server-side; an unauthenticated request resolving
// `viewer` returns null with no error path (the standard Relay shape).
type Query struct {
}

// A registered user of the system. Sensitive fields (email) are only
// exposed to the viewer themselves or principals holding the
// `list_users` capability; otherwise they are nulled out.
type User struct {
	ID          string   `json:"id"`
	Handle      string   `json:"handle"`
	DisplayName *string  `json:"displayName,omitempty"`
	Email       *string  `json:"email,omitempty"`
	CreatedAt   DateTime `json:"createdAt"`
}

// Publishing state of a Post. Mirrors the database enum 1:1.
type PostStatus string

const (
	PostStatusDraft     PostStatus = "DRAFT"
	PostStatusPending   PostStatus = "PENDING"
	PostStatusPublished PostStatus = "PUBLISHED"
	PostStatusScheduled PostStatus = "SCHEDULED"
	PostStatusPrivate   PostStatus = "PRIVATE"
	PostStatusTrashed   PostStatus = "TRASHED"
)

var AllPostStatus = []PostStatus{
	PostStatusDraft,
	PostStatusPending,
	PostStatusPublished,
	PostStatusScheduled,
	PostStatusPrivate,
	PostStatusTrashed,
}

func (e PostStatus) IsValid() bool {
	switch e {
	case PostStatusDraft, PostStatusPending, PostStatusPublished, PostStatusScheduled, PostStatusPrivate, PostStatusTrashed:
		return true
	}
	return false
}

func (e PostStatus) String() string {
	return string(e)
}

func (e *PostStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostStatus", str)
	}
	return nil
}

func (e PostStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PostStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PostStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
