package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/Singleton-Solution/GoNext/apps/api/internal/graphql/dataloader"
	"github.com/Singleton-Solution/GoNext/apps/api/internal/graphql/generated"
	"github.com/Singleton-Solution/GoNext/apps/api/internal/graphql/model"
	"github.com/Singleton-Solution/GoNext/packages/go/policy"
)

// CreatePost is the resolver for the createPost field.
//
// Capability gate: requires `edit_posts`. The author is taken from
// the principal — clients cannot supply an author id directly.
// Slug uniqueness, content sanitisation, and revision recording all
// happen in the persistence layer; this resolver only does the
// authz check and the input -> domain translation.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	p, ok := policy.FromContext(ctx)
	if !ok || p.UserID == "" {
		return nil, errUnauthorized
	}
	if d := r.Policy.Can(p, policy.CapEditPosts, nil); !d.Allowed {
		return nil, errForbidden
	}

	status := string(model.PostStatusDraft)
	if input.Status != nil {
		status = string(*input.Status)
	}

	now := time.Now().UTC()
	row := PostRow{
		Title:     input.Title,
		Slug:      input.Slug,
		Status:    status,
		Excerpt:   input.Excerpt,
		AuthorID:  p.UserID,
		CreatedAt: now,
		UpdatedAt: now,
	}
	out, err := r.PostRepo.Create(ctx, row)
	if err != nil {
		return nil, fmt.Errorf("create post: %w", err)
	}
	return toGraphQLPost(*out), nil
}

// Author is the resolver for the Post.author field. This is what
// dataloaders exist for: instead of issuing one SELECT per post, the
// loader collects all the author ids requested in this tick and
// issues a single SELECT WHERE id = ANY(...). The graph-gophers
// loader handles the scheduling; we only have to call Load.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	if obj == nil {
		return nil, nil
	}
	loaders := dataloader.FromContext(ctx)
	if loaders == nil {
		// Fallback when no loader is attached — typically only in
		// tests that exercise a single-author scenario. Issuing the
		// direct query keeps the resolver well-defined.
		row, err := r.UserRepo.ByID(ctx, obj.AuthorID)
		if err != nil {
			return nil, fmt.Errorf("author: %w", err)
		}
		if row == nil {
			return nil, fmt.Errorf("author: user %s not found", obj.AuthorID)
		}
		return toGraphQLUser(*row, currentUserID(ctx), false), nil
	}

	thunk := loaders.UserByID.Load(ctx, obj.AuthorID)
	row, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("author: %w", err)
	}
	if row == nil {
		return nil, fmt.Errorf("author: user %s not found", obj.AuthorID)
	}
	// Translate the dataloader UserRow into the resolver's UserRow
	// (the duplication is by design — see dataloader/loader.go).
	displayName := row.DisplayName
	createdAt, _ := row.CreatedAt.(time.Time)
	resolverRow := UserRow{
		ID:          row.ID,
		Handle:      row.Handle,
		DisplayName: displayName,
		Email:       row.Email,
		CreatedAt:   createdAt,
	}
	return toGraphQLUser(resolverRow, currentUserID(ctx), false), nil
}

// Viewer is the resolver for the viewer field.
//
// Returns null (not an error) for anonymous requests — this matches
// the Relay convention of "no current user" being a regular value,
// not an exceptional condition. Clients distinguish anonymous from
// "user not found" by checking the field for nil.
func (r *queryResolver) Viewer(ctx context.Context) (*model.User, error) {
	p, ok := policy.FromContext(ctx)
	if !ok || p.UserID == "" {
		return nil, nil
	}
	u, err := r.UserRepo.ByID(ctx, p.UserID)
	if err != nil {
		return nil, fmt.Errorf("viewer: %w", err)
	}
	if u == nil {
		// Principal references a user that no longer exists.
		// Treating it as anonymous is the right call — surfacing it
		// as an error would expose internal state.
		return nil, nil
	}
	// The viewer always sees their own email.
	return toGraphQLUser(*u, p.UserID, false), nil
}

// Post is the resolver for the post field.
//
// Returns null when the post does not exist or the principal cannot
// see it. We do NOT distinguish "not found" from "not authorized" in
// the response — the GraphQL convention is to return null, and the
// indistinguishability prevents enumeration of private content.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	row, err := r.PostRepo.ByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("post: %w", err)
	}
	if row == nil {
		return nil, nil
	}
	if !canSeePost(ctx, r.Policy, *row) {
		return nil, nil
	}
	return toGraphQLPost(*row), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int, after *model.Cursor, filter *model.PostFilter) (*model.PostConnection, error) {
	pageSize := listFirstDefault
	if first != nil {
		pageSize = *first
	}
	if pageSize <= 0 {
		pageSize = listFirstDefault
	}
	if pageSize > listFirstHardCap {
		pageSize = listFirstHardCap
	}

	afterRaw := ""
	if after != nil {
		v, err := model.DecodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("posts: invalid cursor: %w", err)
		}
		afterRaw = v
	}

	repoFilter := PostFilter{}
	if filter != nil {
		if filter.Status != nil {
			s := string(*filter.Status)
			repoFilter.Status = &s
		}
		repoFilter.AuthorID = filter.AuthorID
		repoFilter.TitlePrefix = filter.TitlePrefix
	}

	page, err := r.PostRepo.List(ctx, repoFilter, pageSize, afterRaw)
	if err != nil {
		return nil, fmt.Errorf("posts: %w", err)
	}

	edges := make([]*model.PostEdge, 0, len(page.Rows))
	for _, row := range page.Rows {
		if !canSeePost(ctx, r.Policy, row) {
			continue
		}
		edges = append(edges, &model.PostEdge{
			Cursor: model.EncodeCursor(row.ID),
			Node:   toGraphQLPost(row),
		})
	}

	conn := &model.PostConnection{
		Edges:      edges,
		TotalCount: page.TotalCount,
		PageInfo: &model.PageInfo{
			HasNextPage:     page.HasNext,
			HasPreviousPage: afterRaw != "",
		},
	}
	if len(edges) > 0 {
		first := edges[0].Cursor
		last := edges[len(edges)-1].Cursor
		conn.PageInfo.StartCursor = &first
		conn.PageInfo.EndCursor = &last
	}
	return conn, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	row, err := r.UserRepo.ByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("user: %w", err)
	}
	if row == nil {
		return nil, nil
	}

	// Decide whether the viewer can see sensitive fields. Self always
	// can; otherwise the list_users capability gates.
	var canSeeOthers bool
	viewerID := ""
	if p, ok := policy.FromContext(ctx); ok {
		viewerID = p.UserID
		if d := r.Policy.Can(p, policy.CapListUsers, nil); d.Allowed {
			canSeeOthers = true
		}
	}
	return toGraphQLUser(*row, viewerID, canSeeOthers), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
