// Package hooks defines the plugin-side ABI for the hook bus.
//
// The host-side action+filter bus lives in packages/go/hooks (PR #318).
// The wazero runtime that loads and runs WebAssembly plugins lives in
// packages/go/plugins/runtime (PR #350). This package is the BRIDGE: it
// describes the well-known function the guest module exports so the host
// can dispatch a hook invocation into a plugin, and it provides the host
// half that drives that ABI (marshal, allocate, call, decode).
//
// # Why a dedicated entry point
//
// A plugin manifest (packages/go/plugins/manifest) lists every action
// and filter the plugin subscribes to. At activation time, the lifecycle
// Manager wants to register a host-side callback for each of those hook
// names that proxies through to the plugin. We do NOT want to require
// the guest to export one Go-callable function per hook name, because
// (a) that bloats the export table by O(hooks), (b) it forces the
// toolchain to know the manifest at compile time, and (c) it breaks the
// "register at runtime" model that lets a plugin advertise hooks
// declaratively.
//
// Instead, the plugin exports ONE function — the hook handler entry
// point — and the host passes the hook name as an argument every time.
// The guest does its own internal demultiplex (typically a switch
// statement generated by the plugin SDK). This is the same pattern used
// by every mature WASM plugin host (Envoy proxy-wasm, Spin, Suborbital);
// it is the load-bearing simplification.
//
// # The entry point
//
// Every plugin MUST export a function with the following signature:
//
//	(func (export "gn_handle_hook")
//	      (param $name_ptr i32) (param $name_len i32)
//	      (param $payload_ptr i32) (param $payload_len i32)
//	      (result i64))
//
// Parameters:
//
//   - name_ptr, name_len locate the hook name in the guest's exported
//     linear memory (UTF-8, no NUL terminator). The host writes the
//     bytes BEFORE invoking the function and is responsible for
//     allocating space via the guest's gn_alloc export.
//
//   - payload_ptr, payload_len locate the marshalled payload. The format
//     is defined in marshal.go: a length-prefixed JSON object whose
//     shape depends on whether this is an action or a filter call. Both
//     pointers are within the SAME exported memory. An empty payload
//     (no args; e.g. an action with no payload) is signalled with
//     payload_len == 0; the guest must accept it.
//
// Return value (packed i64):
//
//   - High 32 bits = result_ptr in guest memory.
//   - Low  32 bits = result_len.
//
// Special values, ordered by precedence (a value matching an earlier
// rule never reaches a later one):
//
//	(ptr=0, len=0)   — success, no result body. This is the normal
//	                    return for an action call.
//	(ptr=0, len=N)   where N is one of the ResultStatus* sentinels —
//	                    the call failed. See ResultStatus for the catalog.
//	otherwise        — success, result body is at [ptr, ptr+len) in the
//	                    guest's exported memory. The host reads, copies,
//	                    and frees the bytes via the guest's gn_free export.
//
// Encoding the result via the return register avoids a second host-bound
// callback (which would complicate the ABI) and keeps the call shape
// callable from any toolchain that can return an i64.
//
// # Allocator exports
//
// To pass non-trivial payloads, the host needs to write into guest
// linear memory. wazero exposes the memory directly, but the host
// cannot synthesise an allocation — only the guest knows where its free
// list points. We therefore REQUIRE every plugin to export:
//
//	(func (export "gn_alloc") (param i32) (result i32))   ; size -> ptr
//	(func (export "gn_free")  (param i32) (param i32))    ; ptr, size
//
// gn_alloc returns 0 to signal allocation failure (out of memory). The
// host treats a 0 return as ErrOutOfMemory and abandons the call. The
// guest is free to release the bytes immediately (or never); the host
// only calls gn_free for result buffers and only on the successful path.
// On the error path the host does NOT call gn_free for the input
// allocation — the guest is assumed to own its allocator's state and
// reclaim leaked input buffers on the next call or on shutdown.
//
// # Memory model summary
//
// All bytes crossing the boundary live in the GUEST'S exported "memory"
// (the same memory wazero gives back from Module.Memory()). The host
// never moves bytes the other way without first asking gn_alloc for a
// slot. This is the same convention used by gn_log and gn_panic in the
// runtime's env host module.
//
// The reason for the asymmetry (host writes into guest memory; guest
// writes into guest memory; host reads from guest memory) is that the
// host has no linear memory of its own to expose. wazero modules have
// one memory each, and that memory belongs to the guest. The guest is
// effectively the storage backend; the host is a privileged reader.
//
// # Errors and traps
//
// Two distinct failure modes — distinguished because the bridge handles
// them differently:
//
//   - "Guest reported an error" — gn_handle_hook returned a ResultStatus
//     sentinel. The handler ran to completion but the guest signalled a
//     business-level failure. The bridge returns a HookError wrapping
//     the status; the host bus surfaces it like any other handler error.
//
//   - "Guest trapped" — gn_handle_hook never returned (out-of-bounds
//     memory access, divide by zero, gn_panic, OOM during the call,
//     etc.). The runtime catches the trap and the bridge wraps the
//     resulting *TrapError into a HookError tagged ResultStatusTrap.
//     Callers wanting the original trap can errors.As(err, &TrapError).
//
// # Versioning
//
// This file is the v1 of the hook handler ABI. Any non-additive change
// to the signature (parameter count, return packing, allocator contract)
// will land as a sibling package (abi/hooks/v2, ...) so the v1 surface
// keeps its frozen guarantees.
package hooks

import (
	"errors"
	"fmt"
)

// EntryPoint is the well-known export name every plugin must provide
// for the hook handler ABI. The runtime resolves this name via the
// underlying Module's exported-functions table; missing exports surface
// as a runtime.ErrFunctionNotFound when the bridge first tries to call
// it, which the lifecycle Manager turns into a "plugin is incompatible"
// failure at activation.
const EntryPoint = "gn_handle_hook"

// AllocExport is the well-known name for the guest's allocator. Returns
// 0 for OOM. The bridge calls it before every hook invocation to obtain
// guest memory for the (name, payload) pair.
const AllocExport = "gn_alloc"

// FreeExport is the well-known name for the guest's deallocator. The
// host calls it on the success path to release the result buffer the
// guest produced. The signature is (ptr i32, size i32) — the size hint
// matches gn_alloc's parameter so a bump allocator with a matching free
// can use it.
const FreeExport = "gn_free"

// MaxHookNameLen caps how many bytes the host will transmit for a hook
// name. The manifest schema already constrains hook names to a dotted
// lowercase pattern with no single name > 200 chars, but the bridge
// re-validates so a future schema relaxation doesn't blow up the
// allocator. 256 is the runtime-side ceiling, picked to leave one byte
// of slack against the schema cap.
const MaxHookNameLen = 256

// MaxPayloadBytes caps the per-call payload size the host will pass to
// the guest. This is a sanity guard, not a security boundary — the
// runtime's per-module 16 MiB memory cap is the real ceiling. 1 MiB
// covers every reasonable hook payload (a serialized post, a config
// blob, an audit row) by two orders of magnitude.
//
// A larger payload returns ErrPayloadTooLarge before any guest call.
const MaxPayloadBytes = 1 << 20 // 1 MiB

// MaxResultBytes caps how many bytes the host will read back from the
// guest's returned result pointer. Same sanity-guard rationale as
// MaxPayloadBytes. Set to match: 1 MiB.
const MaxResultBytes = 1 << 20 // 1 MiB

// ResultStatus is the catalog of negative-length sentinels the guest
// can return from gn_handle_hook to signal a typed failure. They occupy
// the low 32 bits of the packed return when the high 32 bits (the
// pointer) are zero — picking the (ptr=0, len=sentinel) shape keeps the
// success path's (ptr, len) interpretation untouched.
//
// Sentinels are negative when interpreted as int32 so they can never
// collide with a legitimate length (which is always non-negative). The
// host decodes the low 32 bits as int32 specifically to enable that
// negativity test.
//
// New sentinels MUST be added at the end; existing values are part of
// the frozen ABI and renumbering would break older plugin builds.
type ResultStatus int32

const (
	// ResultStatusOK is the "success, no body" status. It is what the
	// guest returns from an action handler that has nothing to send
	// back, and it is what the host expects for actions in general.
	//
	// Note this is 0, which matches the (ptr=0, len=0) success-no-body
	// rule from the package-level comment; ResultStatusOK exists as a
	// named constant so guest SDKs and host tests can spell it out.
	ResultStatusOK ResultStatus = 0

	// ResultStatusError is the generic guest-reported error. The
	// handler ran but decided the call failed; the bridge surfaces this
	// as a HookError without a more specific cause. Plugin authors
	// SHOULD use one of the more specific statuses below when they
	// apply; this is the catch-all.
	ResultStatusError ResultStatus = -1

	// ResultStatusOutOfMemory is what the guest returns when its own
	// allocator failed during the handler. The host MAY also synthesise
	// this status when gn_alloc returns 0 for the input buffer, so
	// callers see a single ErrOutOfMemory regardless of which side ran
	// out first.
	ResultStatusOutOfMemory ResultStatus = -2

	// ResultStatusBadPayload indicates the guest could not decode the
	// payload the host sent. This is a contract violation — either the
	// host sent the wrong shape, or the plugin was built against a
	// different ABI version. The bridge surfaces it distinctly so
	// operators can spot incompatible plugins.
	ResultStatusBadPayload ResultStatus = -3

	// ResultStatusUnknownHook is what the guest returns when its
	// dispatch table has no handler for the requested hook name. This
	// shouldn't happen on a correctly-built plugin (the manifest
	// declares which hooks are owned), but a stale plugin binary
	// running against a fresher manifest could produce it.
	ResultStatusUnknownHook ResultStatus = -4

	// ResultStatusTrap is reserved for the host. The guest never
	// returns this; instead the bridge synthesises it when the call
	// trapped (the function never returned at all). It's listed here so
	// the catalog is exhaustive — every HookError carries a status, and
	// trap-derived errors get this one.
	ResultStatusTrap ResultStatus = -5
)

// String returns a short human-readable name for the status. Used in
// error messages and tests; the wire format uses the int32 value.
func (s ResultStatus) String() string {
	switch s {
	case ResultStatusOK:
		return "ok"
	case ResultStatusError:
		return "error"
	case ResultStatusOutOfMemory:
		return "out_of_memory"
	case ResultStatusBadPayload:
		return "bad_payload"
	case ResultStatusUnknownHook:
		return "unknown_hook"
	case ResultStatusTrap:
		return "trap"
	default:
		return fmt.Sprintf("status(%d)", int32(s))
	}
}

// IsError reports whether the status indicates a failure. ResultStatusOK
// is the only non-error status; everything else is a failure mode.
func (s ResultStatus) IsError() bool { return s != ResultStatusOK }

// HookError wraps a typed guest-reported (or host-synthesised) failure
// from a hook invocation. Status is the categorical reason; Hook is the
// hook name the bridge was dispatching when the failure occurred; Cause
// is the underlying error (a runtime *TrapError for traps, nil for pure
// status returns).
//
// HookError implements errors.Is against the sentinel package-level
// errors (ErrOutOfMemory, ErrBadPayload, ...) so callers can match
// without type-asserting.
type HookError struct {
	Hook   string
	Status ResultStatus
	Cause  error
}

// Error returns a one-line description.
func (e *HookError) Error() string {
	if e.Cause != nil {
		return fmt.Sprintf("abi/hooks: %q: %s: %v", e.Hook, e.Status, e.Cause)
	}
	return fmt.Sprintf("abi/hooks: %q: %s", e.Hook, e.Status)
}

// Unwrap returns the underlying cause for errors.As traversal — for
// example, errors.As(err, &runtime.TrapError{}) to inspect a trap.
func (e *HookError) Unwrap() error { return e.Cause }

// Is supports errors.Is matching against the sentinel package-level
// errors below. The match is by status, so any HookError with
// ResultStatusOutOfMemory matches ErrOutOfMemory regardless of which
// guest produced it.
func (e *HookError) Is(target error) bool {
	switch target {
	case ErrOutOfMemory:
		return e.Status == ResultStatusOutOfMemory
	case ErrBadPayload:
		return e.Status == ResultStatusBadPayload
	case ErrUnknownHook:
		return e.Status == ResultStatusUnknownHook
	case ErrGuestError:
		return e.Status == ResultStatusError
	case ErrTrapped:
		return e.Status == ResultStatusTrap
	}
	return false
}

// Sentinel errors for matching with errors.Is. Each one corresponds to
// a ResultStatus; the HookError.Is method routes between them.
//
// Callers SHOULD prefer errors.Is over status comparisons so the
// bridge can refactor the underlying status numbering without breaking
// the consumer surface.
var (
	// ErrOutOfMemory is returned (or wrapped) when either the host's
	// allocation into guest memory failed (gn_alloc returned 0) or the
	// guest reported ResultStatusOutOfMemory from inside the handler.
	// The two failure modes share an error sentinel because the
	// distinction (whose allocator failed first) is rarely useful to
	// the host caller — the action either ran or it didn't.
	ErrOutOfMemory = errors.New("abi/hooks: out of memory")

	// ErrBadPayload is returned when the guest reported it could not
	// decode the payload. Indicates an ABI mismatch between host and
	// guest — surfaced distinctly so operators can identify stale plugins.
	ErrBadPayload = errors.New("abi/hooks: bad payload")

	// ErrUnknownHook is returned when the guest reported it has no
	// handler for the requested hook name. Typically means the manifest
	// drifted from the binary.
	ErrUnknownHook = errors.New("abi/hooks: unknown hook")

	// ErrGuestError is returned when the guest reported a generic
	// failure (ResultStatusError). It's the catch-all for the plugin
	// signalling "I ran, I failed" without further detail.
	ErrGuestError = errors.New("abi/hooks: guest error")

	// ErrTrapped is returned when the call trapped before the guest
	// could produce a status. The underlying *TrapError is reachable via
	// errors.As on the wrapping HookError.
	ErrTrapped = errors.New("abi/hooks: guest trapped")

	// ErrPayloadTooLarge is returned BEFORE any guest call when the
	// marshalled payload exceeds MaxPayloadBytes. Distinct from
	// ErrOutOfMemory because no allocation was even attempted.
	ErrPayloadTooLarge = errors.New("abi/hooks: payload exceeds host cap")

	// ErrResultTooLarge is returned when the guest's result pointer
	// claims a length greater than MaxResultBytes. The host refuses to
	// read it; the call surfaces as a HookError wrapping this sentinel.
	ErrResultTooLarge = errors.New("abi/hooks: result exceeds host cap")

	// ErrMissingExport is returned when the plugin module does not
	// export one of the required ABI functions (gn_handle_hook,
	// gn_alloc, gn_free). It wraps the underlying
	// runtime.ErrFunctionNotFound for callers that want to inspect
	// which export was missing.
	ErrMissingExport = errors.New("abi/hooks: required export missing")

	// ErrMemoryUnavailable is returned when the plugin module does not
	// export linear memory. Without memory the host cannot pass any
	// argument and cannot read any result; the bridge refuses to call.
	ErrMemoryUnavailable = errors.New("abi/hooks: memory unavailable")

	// ErrHookNameTooLong is returned when the hook name exceeds
	// MaxHookNameLen bytes. The manifest schema rejects most cases at
	// install time; this is the runtime backstop.
	ErrHookNameTooLong = errors.New("abi/hooks: hook name too long")
)

// packResult composes the i64 the guest returns from gn_handle_hook
// from a (ptr, len) pair. Exported for use by guest SDK helpers and
// tests; host code uses unpackResult on the way back.
//
// Pointer is treated as uint32 (it's a memory offset, always
// non-negative); length is treated as int32 so callers can encode a
// negative ResultStatus by passing (0, int32(status)).
func packResult(ptr uint32, length int32) uint64 {
	return uint64(ptr)<<32 | uint64(uint32(length))
}

// unpackResult is the inverse of packResult. Returns the high-half ptr
// and the low-half length, with length re-interpreted as int32 so a
// negative ResultStatus survives the round trip.
func unpackResult(packed uint64) (ptr uint32, length int32) {
	ptr = uint32(packed >> 32)
	length = int32(packed & 0xFFFFFFFF)
	return ptr, length
}
