package initcmd

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/Singleton-Solution/GoNext/packages/go/auth/password"
)

// ErrAdminExists is returned by createAdmin when a user with the
// supplied email already exists. The CLI wraps this with a hint
// pointing the operator at `--admin-password-reset` (a future flag;
// see issue body) so they don't accidentally clobber the existing
// row.
var ErrAdminExists = errors.New("admin already exists, use --admin-password-reset")

// userRow is the minimal projection createAdmin needs after the
// INSERT. id is the canonical UUID v7 generated by the gen_uuid_v7()
// default; we read it back via RETURNING so callers can fold the
// value into subsequent writes without a second probe.
type userRow struct {
	id    uuid.UUID
	email string
}

// adminInput is the validated, typed payload createAdmin operates on.
// We split this from the flag-parsing struct in init.go so the
// orchestrator (setup.go) can drive createAdmin in unit tests without
// having to populate the unrelated --skip-* flags.
type adminInput struct {
	email    string
	password string
	pepper   []byte
}

// createAdmin inserts the initial super_admin row and its argon2id
// password material. The flow is a single transaction:
//
//  1. Probe users.email for an existing row. If present, return
//     ErrAdminExists wrapped with the email so the operator can
//     confirm they typed the right address.
//  2. Hash the password via packages/go/auth/password (argon2id +
//     HMAC pepper). Per the issue body, we deliberately skip email
//     confirmation: the operator is the one creating their own
//     account, so users.email_verified_at is stamped to now() and
//     the welcome-email side effect is bypassed.
//  3. INSERT users with meta = { "roles": ["super_admin"] }. The
//     roles array is read by packages/go/middleware/auth at session
//     hydration time (see rolesFromData); storing the role in
//     users.meta avoids the migration we'd need to add a real
//     user_roles table — that's docs/06 §6 future work and out of
//     scope for the boot story.
//  4. INSERT user_passwords with the PHC string from step 2.
//
// On success the function returns the new user's UUID. On any
// failure the transaction is rolled back by the deferred Rollback;
// pgx considers Rollback after Commit a no-op so the defer is safe.
func createAdmin(ctx context.Context, tx pgx.Tx, in adminInput) (uuid.UUID, error) {
	if err := validatePassword(in.password); err != nil {
		return uuid.UUID{}, err
	}
	emailNorm, err := validateEmail(in.email)
	if err != nil {
		return uuid.UUID{}, err
	}

	// Existing-admin probe. We compare against the citext column so
	// "Admin@Example.com" and "admin@example.com" collide — the
	// migration's CITEXT UNIQUE constraint would catch this on the
	// INSERT, but we want a friendly error before we burn ~80ms on
	// the argon2id hash.
	var existingID uuid.UUID
	err = tx.QueryRow(ctx,
		`SELECT id FROM users WHERE email = $1::citext LIMIT 1`,
		emailNorm,
	).Scan(&existingID)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
		// Happy path — no existing row, fall through to the insert.
	case err != nil:
		return uuid.UUID{}, fmt.Errorf("probe existing admin: %w", err)
	default:
		return uuid.UUID{}, fmt.Errorf("%w: %s", ErrAdminExists, emailNorm)
	}

	hashed, err := password.Hash(in.password, in.pepper)
	if err != nil {
		return uuid.UUID{}, fmt.Errorf("hash password: %w", err)
	}

	// Pre-serialize the meta JSON so we can hand the driver a string
	// (which JSONB columns accept verbatim). Using json.Marshal here
	// rather than a string literal keeps us safe if the role slug ever
	// needs escaping — defensive, not currently exploitable.
	metaBytes, err := json.Marshal(map[string]any{
		"roles": []string{"super_admin"},
	})
	if err != nil {
		return uuid.UUID{}, fmt.Errorf("marshal user meta: %w", err)
	}

	// Synthesize a handle from the local-part of the email. handle is
	// CITEXT UNIQUE, so a future operator initing a second instance
	// with the same email local part would collide — we accept that
	// trade because (a) `init` runs against a fresh DB exactly once
	// and (b) the operator can rename later from the admin UI.
	handle := localPart(emailNorm)

	var row userRow
	if err := tx.QueryRow(ctx, `
		INSERT INTO users (email, handle, display_name, email_verified_at, meta)
		VALUES ($1::citext, $2::citext, $3, now(), $4::jsonb)
		RETURNING id, email::text
	`, emailNorm, handle, "Administrator", string(metaBytes)).Scan(&row.id, &row.email); err != nil {
		return uuid.UUID{}, fmt.Errorf("insert admin user: %w", err)
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO user_passwords (user_id, password_hash)
		VALUES ($1, $2)
	`, row.id, hashed); err != nil {
		return uuid.UUID{}, fmt.Errorf("insert admin password: %w", err)
	}

	return row.id, nil
}

// localPart returns the substring before '@' in an email. We've
// already validated the address with mail.ParseAddress so the '@' is
// guaranteed present, but we guard with an index-of check anyway —
// belt-and-braces against a future caller that bypasses validation.
func localPart(email string) string {
	for i := 0; i < len(email); i++ {
		if email[i] == '@' {
			return email[:i]
		}
	}
	return email
}
